// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artifacts.sql

package store

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createArtifact = `-- name: CreateArtifact :one
INSERT INTO artifacts (
  type, generation_type, status, eval_id, eval_item_id, attempt_id, reviewer_id,
  text, output_json, model, prompt, prompt_template_id, schema_template_id,
  model_params, prompt_render, input_hash, meta, error
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
) RETURNING id, type, status, eval_id, eval_item_id, attempt_id, reviewer_id, text, output_json, model, prompt, input_hash, meta, error, created_at, prompt_template_id, schema_template_id, model_params, prompt_render, generation_type
`

type CreateArtifactParams struct {
	Type             string                `json:"type"`
	GenerationType   NullGenerationType    `json:"generation_type"`
	Status           string                `json:"status"`
	EvalID           uuid.NullUUID         `json:"eval_id"`
	EvalItemID       uuid.NullUUID         `json:"eval_item_id"`
	AttemptID        uuid.NullUUID         `json:"attempt_id"`
	ReviewerID       uuid.NullUUID         `json:"reviewer_id"`
	Text             sql.NullString        `json:"text"`
	OutputJson       pqtype.NullRawMessage `json:"output_json"`
	Model            sql.NullString        `json:"model"`
	Prompt           sql.NullString        `json:"prompt"`
	PromptTemplateID uuid.NullUUID         `json:"prompt_template_id"`
	SchemaTemplateID uuid.NullUUID         `json:"schema_template_id"`
	ModelParams      pqtype.NullRawMessage `json:"model_params"`
	PromptRender     sql.NullString        `json:"prompt_render"`
	InputHash        sql.NullString        `json:"input_hash"`
	Meta             pqtype.NullRawMessage `json:"meta"`
	Error            sql.NullString        `json:"error"`
}

func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, createArtifact,
		arg.Type,
		arg.GenerationType,
		arg.Status,
		arg.EvalID,
		arg.EvalItemID,
		arg.AttemptID,
		arg.ReviewerID,
		arg.Text,
		arg.OutputJson,
		arg.Model,
		arg.Prompt,
		arg.PromptTemplateID,
		arg.SchemaTemplateID,
		arg.ModelParams,
		arg.PromptRender,
		arg.InputHash,
		arg.Meta,
		arg.Error,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.EvalID,
		&i.EvalItemID,
		&i.AttemptID,
		&i.ReviewerID,
		&i.Text,
		&i.OutputJson,
		&i.Model,
		&i.Prompt,
		&i.InputHash,
		&i.Meta,
		&i.Error,
		&i.CreatedAt,
		&i.PromptTemplateID,
		&i.SchemaTemplateID,
		&i.ModelParams,
		&i.PromptRender,
		&i.GenerationType,
	)
	return i, err
}

const getArtifact = `-- name: GetArtifact :one
SELECT id, type, status, eval_id, eval_item_id, attempt_id, reviewer_id, text, output_json, model, prompt, input_hash, meta, error, created_at, prompt_template_id, schema_template_id, model_params, prompt_render, generation_type FROM artifacts WHERE id = $1 LIMIT 1
`

func (q *Queries) GetArtifact(ctx context.Context, id uuid.UUID) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, getArtifact, id)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.EvalID,
		&i.EvalItemID,
		&i.AttemptID,
		&i.ReviewerID,
		&i.Text,
		&i.OutputJson,
		&i.Model,
		&i.Prompt,
		&i.InputHash,
		&i.Meta,
		&i.Error,
		&i.CreatedAt,
		&i.PromptTemplateID,
		&i.SchemaTemplateID,
		&i.ModelParams,
		&i.PromptRender,
		&i.GenerationType,
	)
	return i, err
}

const getArtifactStats = `-- name: GetArtifactStats :one
SELECT 
  COUNT(*) as total_artifacts,
  COUNT(CASE WHEN status = 'READY' THEN 1 END) as ready_count,
  COUNT(CASE WHEN status = 'PENDING' THEN 1 END) as pending_count,
  COUNT(CASE WHEN status = 'ERROR' THEN 1 END) as error_count,
  COUNT(CASE WHEN error IS NOT NULL THEN 1 END) as with_errors
FROM artifacts
`

type GetArtifactStatsRow struct {
	TotalArtifacts int64 `json:"total_artifacts"`
	ReadyCount     int64 `json:"ready_count"`
	PendingCount   int64 `json:"pending_count"`
	ErrorCount     int64 `json:"error_count"`
	WithErrors     int64 `json:"with_errors"`
}

func (q *Queries) GetArtifactStats(ctx context.Context) (GetArtifactStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getArtifactStats)
	var i GetArtifactStatsRow
	err := row.Scan(
		&i.TotalArtifacts,
		&i.ReadyCount,
		&i.PendingCount,
		&i.ErrorCount,
		&i.WithErrors,
	)
	return i, err
}

const getArtifactsByAttempt = `-- name: GetArtifactsByAttempt :many
SELECT id, type, status, eval_id, eval_item_id, attempt_id, reviewer_id, text, output_json, model, prompt, input_hash, meta, error, created_at, prompt_template_id, schema_template_id, model_params, prompt_render, generation_type FROM artifacts WHERE attempt_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetArtifactsByAttempt(ctx context.Context, attemptID uuid.NullUUID) ([]Artifact, error) {
	rows, err := q.db.QueryContext(ctx, getArtifactsByAttempt, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Status,
			&i.EvalID,
			&i.EvalItemID,
			&i.AttemptID,
			&i.ReviewerID,
			&i.Text,
			&i.OutputJson,
			&i.Model,
			&i.Prompt,
			&i.InputHash,
			&i.Meta,
			&i.Error,
			&i.CreatedAt,
			&i.PromptTemplateID,
			&i.SchemaTemplateID,
			&i.ModelParams,
			&i.PromptRender,
			&i.GenerationType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArtifactsByEval = `-- name: GetArtifactsByEval :many
SELECT id, type, status, eval_id, eval_item_id, attempt_id, reviewer_id, text, output_json, model, prompt, input_hash, meta, error, created_at, prompt_template_id, schema_template_id, model_params, prompt_render, generation_type FROM artifacts WHERE eval_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetArtifactsByEval(ctx context.Context, evalID uuid.NullUUID) ([]Artifact, error) {
	rows, err := q.db.QueryContext(ctx, getArtifactsByEval, evalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Status,
			&i.EvalID,
			&i.EvalItemID,
			&i.AttemptID,
			&i.ReviewerID,
			&i.Text,
			&i.OutputJson,
			&i.Model,
			&i.Prompt,
			&i.InputHash,
			&i.Meta,
			&i.Error,
			&i.CreatedAt,
			&i.PromptTemplateID,
			&i.SchemaTemplateID,
			&i.ModelParams,
			&i.PromptRender,
			&i.GenerationType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArtifactsByEvalItem = `-- name: GetArtifactsByEvalItem :many
SELECT id, type, status, eval_id, eval_item_id, attempt_id, reviewer_id, text, output_json, model, prompt, input_hash, meta, error, created_at, prompt_template_id, schema_template_id, model_params, prompt_render, generation_type FROM artifacts WHERE eval_item_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetArtifactsByEvalItem(ctx context.Context, evalItemID uuid.NullUUID) ([]Artifact, error) {
	rows, err := q.db.QueryContext(ctx, getArtifactsByEvalItem, evalItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Status,
			&i.EvalID,
			&i.EvalItemID,
			&i.AttemptID,
			&i.ReviewerID,
			&i.Text,
			&i.OutputJson,
			&i.Model,
			&i.Prompt,
			&i.InputHash,
			&i.Meta,
			&i.Error,
			&i.CreatedAt,
			&i.PromptTemplateID,
			&i.SchemaTemplateID,
			&i.ModelParams,
			&i.PromptRender,
			&i.GenerationType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArtifactsByInputHash = `-- name: GetArtifactsByInputHash :many
SELECT id, type, status, eval_id, eval_item_id, attempt_id, reviewer_id, text, output_json, model, prompt, input_hash, meta, error, created_at, prompt_template_id, schema_template_id, model_params, prompt_render, generation_type FROM artifacts 
WHERE input_hash = $1 
ORDER BY created_at DESC
`

func (q *Queries) GetArtifactsByInputHash(ctx context.Context, inputHash sql.NullString) ([]Artifact, error) {
	rows, err := q.db.QueryContext(ctx, getArtifactsByInputHash, inputHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Status,
			&i.EvalID,
			&i.EvalItemID,
			&i.AttemptID,
			&i.ReviewerID,
			&i.Text,
			&i.OutputJson,
			&i.Model,
			&i.Prompt,
			&i.InputHash,
			&i.Meta,
			&i.Error,
			&i.CreatedAt,
			&i.PromptTemplateID,
			&i.SchemaTemplateID,
			&i.ModelParams,
			&i.PromptRender,
			&i.GenerationType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArtifactsByReviewer = `-- name: GetArtifactsByReviewer :many
SELECT id, type, status, eval_id, eval_item_id, attempt_id, reviewer_id, text, output_json, model, prompt, input_hash, meta, error, created_at, prompt_template_id, schema_template_id, model_params, prompt_render, generation_type FROM artifacts WHERE reviewer_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetArtifactsByReviewer(ctx context.Context, reviewerID uuid.NullUUID) ([]Artifact, error) {
	rows, err := q.db.QueryContext(ctx, getArtifactsByReviewer, reviewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Status,
			&i.EvalID,
			&i.EvalItemID,
			&i.AttemptID,
			&i.ReviewerID,
			&i.Text,
			&i.OutputJson,
			&i.Model,
			&i.Prompt,
			&i.InputHash,
			&i.Meta,
			&i.Error,
			&i.CreatedAt,
			&i.PromptTemplateID,
			&i.SchemaTemplateID,
			&i.ModelParams,
			&i.PromptRender,
			&i.GenerationType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArtifactsByStatus = `-- name: GetArtifactsByStatus :many
SELECT id, type, status, eval_id, eval_item_id, attempt_id, reviewer_id, text, output_json, model, prompt, input_hash, meta, error, created_at, prompt_template_id, schema_template_id, model_params, prompt_render, generation_type FROM artifacts WHERE status = $1 ORDER BY created_at DESC
`

func (q *Queries) GetArtifactsByStatus(ctx context.Context, status string) ([]Artifact, error) {
	rows, err := q.db.QueryContext(ctx, getArtifactsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Status,
			&i.EvalID,
			&i.EvalItemID,
			&i.AttemptID,
			&i.ReviewerID,
			&i.Text,
			&i.OutputJson,
			&i.Model,
			&i.Prompt,
			&i.InputHash,
			&i.Meta,
			&i.Error,
			&i.CreatedAt,
			&i.PromptTemplateID,
			&i.SchemaTemplateID,
			&i.ModelParams,
			&i.PromptRender,
			&i.GenerationType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArtifactsByType = `-- name: GetArtifactsByType :many
SELECT id, type, status, eval_id, eval_item_id, attempt_id, reviewer_id, text, output_json, model, prompt, input_hash, meta, error, created_at, prompt_template_id, schema_template_id, model_params, prompt_render, generation_type FROM artifacts WHERE type = $1 ORDER BY created_at DESC
`

func (q *Queries) GetArtifactsByType(ctx context.Context, type_ string) ([]Artifact, error) {
	rows, err := q.db.QueryContext(ctx, getArtifactsByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Status,
			&i.EvalID,
			&i.EvalItemID,
			&i.AttemptID,
			&i.ReviewerID,
			&i.Text,
			&i.OutputJson,
			&i.Model,
			&i.Prompt,
			&i.InputHash,
			&i.Meta,
			&i.Error,
			&i.CreatedAt,
			&i.PromptTemplateID,
			&i.SchemaTemplateID,
			&i.ModelParams,
			&i.PromptRender,
			&i.GenerationType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArtifactsByTypeAndEntity = `-- name: GetArtifactsByTypeAndEntity :many
SELECT id, type, status, eval_id, eval_item_id, attempt_id, reviewer_id, text, output_json, model, prompt, input_hash, meta, error, created_at, prompt_template_id, schema_template_id, model_params, prompt_render, generation_type FROM artifacts 
WHERE type = $1 
AND (
  (eval_id = $2 AND $2 IS NOT NULL) OR
  (eval_item_id = $3 AND $3 IS NOT NULL) OR
  (attempt_id = $4 AND $4 IS NOT NULL)
)
ORDER BY created_at DESC
`

type GetArtifactsByTypeAndEntityParams struct {
	Type       string        `json:"type"`
	EvalID     uuid.NullUUID `json:"eval_id"`
	EvalItemID uuid.NullUUID `json:"eval_item_id"`
	AttemptID  uuid.NullUUID `json:"attempt_id"`
}

func (q *Queries) GetArtifactsByTypeAndEntity(ctx context.Context, arg GetArtifactsByTypeAndEntityParams) ([]Artifact, error) {
	rows, err := q.db.QueryContext(ctx, getArtifactsByTypeAndEntity,
		arg.Type,
		arg.EvalID,
		arg.EvalItemID,
		arg.AttemptID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Status,
			&i.EvalID,
			&i.EvalItemID,
			&i.AttemptID,
			&i.ReviewerID,
			&i.Text,
			&i.OutputJson,
			&i.Model,
			&i.Prompt,
			&i.InputHash,
			&i.Meta,
			&i.Error,
			&i.CreatedAt,
			&i.PromptTemplateID,
			&i.SchemaTemplateID,
			&i.ModelParams,
			&i.PromptRender,
			&i.GenerationType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestArtifactByTypeAndEntity = `-- name: GetLatestArtifactByTypeAndEntity :one
SELECT id, type, status, eval_id, eval_item_id, attempt_id, reviewer_id, text, output_json, model, prompt, input_hash, meta, error, created_at, prompt_template_id, schema_template_id, model_params, prompt_render, generation_type FROM artifacts 
WHERE type = $1 
AND (
  (eval_id = $2 AND $2 IS NOT NULL) OR
  (eval_item_id = $3 AND $3 IS NOT NULL) OR
  (attempt_id = $4 AND $4 IS NOT NULL)
)
ORDER BY created_at DESC 
LIMIT 1
`

type GetLatestArtifactByTypeAndEntityParams struct {
	Type       string        `json:"type"`
	EvalID     uuid.NullUUID `json:"eval_id"`
	EvalItemID uuid.NullUUID `json:"eval_item_id"`
	AttemptID  uuid.NullUUID `json:"attempt_id"`
}

func (q *Queries) GetLatestArtifactByTypeAndEntity(ctx context.Context, arg GetLatestArtifactByTypeAndEntityParams) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, getLatestArtifactByTypeAndEntity,
		arg.Type,
		arg.EvalID,
		arg.EvalItemID,
		arg.AttemptID,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.EvalID,
		&i.EvalItemID,
		&i.AttemptID,
		&i.ReviewerID,
		&i.Text,
		&i.OutputJson,
		&i.Model,
		&i.Prompt,
		&i.InputHash,
		&i.Meta,
		&i.Error,
		&i.CreatedAt,
		&i.PromptTemplateID,
		&i.SchemaTemplateID,
		&i.ModelParams,
		&i.PromptRender,
		&i.GenerationType,
	)
	return i, err
}

const countArtifacts = `-- name: CountArtifacts :one
SELECT COUNT(*) FROM artifacts
`

func (q *Queries) CountArtifacts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countArtifacts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countArtifactsByType = `-- name: CountArtifactsByType :one
SELECT COUNT(*) FROM artifacts 
WHERE type = $1
`

func (q *Queries) CountArtifactsByType(ctx context.Context, type_ string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countArtifactsByType, type_)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listArtifactsByType = `-- name: ListArtifactsByType :many
SELECT id, type, status, eval_id, eval_item_id, attempt_id, reviewer_id, text, output_json, model, prompt, input_hash, meta, error, created_at, prompt_template_id, schema_template_id, model_params, prompt_render, generation_type FROM artifacts 
WHERE type = $1 
ORDER BY created_at DESC 
LIMIT $2 OFFSET $3
`

type ListArtifactsByTypeParams struct {
	Type   string `json:"type"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListArtifactsByType(ctx context.Context, arg ListArtifactsByTypeParams) ([]Artifact, error) {
	rows, err := q.db.QueryContext(ctx, listArtifactsByType, arg.Type, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Status,
			&i.EvalID,
			&i.EvalItemID,
			&i.AttemptID,
			&i.ReviewerID,
			&i.Text,
			&i.OutputJson,
			&i.Model,
			&i.Prompt,
			&i.InputHash,
			&i.Meta,
			&i.Error,
			&i.CreatedAt,
			&i.PromptTemplateID,
			&i.SchemaTemplateID,
			&i.ModelParams,
			&i.PromptRender,
			&i.GenerationType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifacts = `-- name: ListArtifacts :many
SELECT id, type, status, eval_id, eval_item_id, attempt_id, reviewer_id, text, output_json, model, prompt, input_hash, meta, error, created_at, prompt_template_id, schema_template_id, model_params, prompt_render, generation_type FROM artifacts ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListArtifactsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListArtifacts(ctx context.Context, arg ListArtifactsParams) ([]Artifact, error) {
	rows, err := q.db.QueryContext(ctx, listArtifacts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Status,
			&i.EvalID,
			&i.EvalItemID,
			&i.AttemptID,
			&i.ReviewerID,
			&i.Text,
			&i.OutputJson,
			&i.Model,
			&i.Prompt,
			&i.InputHash,
			&i.Meta,
			&i.Error,
			&i.CreatedAt,
			&i.PromptTemplateID,
			&i.SchemaTemplateID,
			&i.ModelParams,
			&i.PromptRender,
			&i.GenerationType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
