// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chunking_configs.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const activateChunkingConfig = `-- name: ActivateChunkingConfig :exec
UPDATE chunking_configs SET is_active = true WHERE id = $1
`

func (q *Queries) ActivateChunkingConfig(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, activateChunkingConfig, id)
	return err
}

const createChunkingConfig = `-- name: CreateChunkingConfig :one
INSERT INTO chunking_configs (
  version, chunk_size, chunk_overlap, is_active, created_by
) VALUES (
  (SELECT COALESCE(MAX(version), 0) + 1 FROM chunking_configs),
  $1, $2, $3, $4
) RETURNING id, version, chunk_size, chunk_overlap, is_active, created_by, created_at
`

type CreateChunkingConfigParams struct {
	ChunkSize    int32     `json:"chunk_size"`
	ChunkOverlap int32     `json:"chunk_overlap"`
	IsActive     bool      `json:"is_active"`
	CreatedBy    uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateChunkingConfig(ctx context.Context, arg CreateChunkingConfigParams) (ChunkingConfig, error) {
	row := q.db.QueryRowContext(ctx, createChunkingConfig,
		arg.ChunkSize,
		arg.ChunkOverlap,
		arg.IsActive,
		arg.CreatedBy,
	)
	var i ChunkingConfig
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.ChunkSize,
		&i.ChunkOverlap,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateOtherChunkingConfigs = `-- name: DeactivateOtherChunkingConfigs :exec
UPDATE chunking_configs SET is_active = false WHERE id != $1
`

func (q *Queries) DeactivateOtherChunkingConfigs(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deactivateOtherChunkingConfigs, id)
	return err
}

const getActiveChunkingConfig = `-- name: GetActiveChunkingConfig :one
SELECT id, version, chunk_size, chunk_overlap, is_active, created_by, created_at FROM chunking_configs WHERE is_active = true LIMIT 1
`

func (q *Queries) GetActiveChunkingConfig(ctx context.Context) (ChunkingConfig, error) {
	row := q.db.QueryRowContext(ctx, getActiveChunkingConfig)
	var i ChunkingConfig
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.ChunkSize,
		&i.ChunkOverlap,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getChunkingConfig = `-- name: GetChunkingConfig :one
SELECT id, version, chunk_size, chunk_overlap, is_active, created_by, created_at FROM chunking_configs WHERE id = $1 LIMIT 1
`

func (q *Queries) GetChunkingConfig(ctx context.Context, id uuid.UUID) (ChunkingConfig, error) {
	row := q.db.QueryRowContext(ctx, getChunkingConfig, id)
	var i ChunkingConfig
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.ChunkSize,
		&i.ChunkOverlap,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listChunkingConfigs = `-- name: ListChunkingConfigs :many
SELECT id, version, chunk_size, chunk_overlap, is_active, created_by, created_at FROM chunking_configs ORDER BY created_at DESC
`

func (q *Queries) ListChunkingConfigs(ctx context.Context) ([]ChunkingConfig, error) {
	rows, err := q.db.QueryContext(ctx, listChunkingConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChunkingConfig
	for rows.Next() {
		var i ChunkingConfig
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.ChunkSize,
			&i.ChunkOverlap,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
