// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: curricula.sql

package store

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCurriculum = `-- name: CreateCurriculum :one
INSERT INTO curricula (
  subject_id, parent_id, label, code, description, order_index,
  grade_level, is_active
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, subject_id, parent_id, label, code, description, order_index, grade_level, is_active, created_at, updated_at
`

type CreateCurriculumParams struct {
	SubjectID   uuid.UUID      `json:"subject_id"`
	ParentID    uuid.NullUUID  `json:"parent_id"`
	Label       string         `json:"label"`
	Code        sql.NullString `json:"code"`
	Description sql.NullString `json:"description"`
	OrderIndex  int32          `json:"order_index"`
	GradeLevel  sql.NullString `json:"grade_level"`
	IsActive    bool           `json:"is_active"`
}

func (q *Queries) CreateCurriculum(ctx context.Context, arg CreateCurriculumParams) (Curricula, error) {
	row := q.db.QueryRowContext(ctx, createCurriculum,
		arg.SubjectID,
		arg.ParentID,
		arg.Label,
		arg.Code,
		arg.Description,
		arg.OrderIndex,
		arg.GradeLevel,
		arg.IsActive,
	)
	var i Curricula
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.ParentID,
		&i.Label,
		&i.Code,
		&i.Description,
		&i.OrderIndex,
		&i.GradeLevel,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCurriculum = `-- name: DeleteCurriculum :exec
DELETE FROM curricula WHERE id = $1
`

func (q *Queries) DeleteCurriculum(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCurriculum, id)
	return err
}

const getCurriculum = `-- name: GetCurriculum :one
SELECT id, subject_id, parent_id, label, code, description, order_index, grade_level, is_active, created_at, updated_at FROM curricula WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCurriculum(ctx context.Context, id uuid.UUID) (Curricula, error) {
	row := q.db.QueryRowContext(ctx, getCurriculum, id)
	var i Curricula
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.ParentID,
		&i.Label,
		&i.Code,
		&i.Description,
		&i.OrderIndex,
		&i.GradeLevel,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCurriculaByParent = `-- name: ListCurriculaByParent :many
SELECT id, subject_id, parent_id, label, code, description, order_index, grade_level, is_active, created_at, updated_at FROM curricula
WHERE parent_id = $1
ORDER BY order_index ASC, created_at ASC
`

func (q *Queries) ListCurriculaByParent(ctx context.Context, parentID uuid.NullUUID) ([]Curricula, error) {
	rows, err := q.db.QueryContext(ctx, listCurriculaByParent, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Curricula
	for rows.Next() {
		var i Curricula
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.ParentID,
			&i.Label,
			&i.Code,
			&i.Description,
			&i.OrderIndex,
			&i.GradeLevel,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurriculaBySubject = `-- name: ListCurriculaBySubject :many
SELECT id, subject_id, parent_id, label, code, description, order_index, grade_level, is_active, created_at, updated_at FROM curricula
WHERE subject_id = $1
ORDER BY order_index ASC, created_at ASC
`

func (q *Queries) ListCurriculaBySubject(ctx context.Context, subjectID uuid.UUID) ([]Curricula, error) {
	rows, err := q.db.QueryContext(ctx, listCurriculaBySubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Curricula
	for rows.Next() {
		var i Curricula
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.ParentID,
			&i.Label,
			&i.Code,
			&i.Description,
			&i.OrderIndex,
			&i.GradeLevel,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootCurriculaBySubject = `-- name: ListRootCurriculaBySubject :many
SELECT id, subject_id, parent_id, label, code, description, order_index, grade_level, is_active, created_at, updated_at FROM curricula
WHERE subject_id = $1 AND parent_id IS NULL
ORDER BY order_index ASC, created_at ASC
`

func (q *Queries) ListRootCurriculaBySubject(ctx context.Context, subjectID uuid.UUID) ([]Curricula, error) {
	rows, err := q.db.QueryContext(ctx, listRootCurriculaBySubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Curricula
	for rows.Next() {
		var i Curricula
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.ParentID,
			&i.Label,
			&i.Code,
			&i.Description,
			&i.OrderIndex,
			&i.GradeLevel,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCurriculum = `-- name: UpdateCurriculum :one
UPDATE curricula SET
  subject_id = COALESCE($2, subject_id),
  parent_id = COALESCE($3, parent_id),
  label = COALESCE($4, label),
  code = COALESCE($5, code),
  description = COALESCE($6, description),
  order_index = COALESCE($7, order_index),
  grade_level = COALESCE($8, grade_level),
  is_active = COALESCE($9, is_active),
  updated_at = now()
WHERE id = $1
RETURNING id, subject_id, parent_id, label, code, description, order_index, grade_level, is_active, created_at, updated_at
`

type UpdateCurriculumParams struct {
	ID          uuid.UUID      `json:"id"`
	SubjectID   uuid.UUID      `json:"subject_id"`
	ParentID    uuid.NullUUID  `json:"parent_id"`
	Label       string         `json:"label"`
	Code        sql.NullString `json:"code"`
	Description sql.NullString `json:"description"`
	OrderIndex  int32          `json:"order_index"`
	GradeLevel  sql.NullString `json:"grade_level"`
	IsActive    bool           `json:"is_active"`
}

func (q *Queries) UpdateCurriculum(ctx context.Context, arg UpdateCurriculumParams) (Curricula, error) {
	row := q.db.QueryRowContext(ctx, updateCurriculum,
		arg.ID,
		arg.SubjectID,
		arg.ParentID,
		arg.Label,
		arg.Code,
		arg.Description,
		arg.OrderIndex,
		arg.GradeLevel,
		arg.IsActive,
	)
	var i Curricula
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.ParentID,
		&i.Label,
		&i.Code,
		&i.Description,
		&i.OrderIndex,
		&i.GradeLevel,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
