// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents.sql

package store

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
  filename, title, mime_type, content, storage_path, rag_status, 
  user_id, subject_id, curriculum_id, curricular, subjects
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, filename, title, mime_type, content, storage_path, rag_status, user_id, subject_id, created_at, updated_at, curricular, subjects, curriculum_id
`

type CreateDocumentParams struct {
	Filename     string         `json:"filename"`
	Title        sql.NullString `json:"title"`
	MimeType     sql.NullString `json:"mime_type"`
	Content      sql.NullString `json:"content"`
	StoragePath  sql.NullString `json:"storage_path"`
	RagStatus    string         `json:"rag_status"`
	UserID       uuid.UUID      `json:"user_id"`
	SubjectID    uuid.NullUUID  `json:"subject_id"`
	CurriculumID uuid.NullUUID  `json:"curriculum_id"`
	Curricular   sql.NullString `json:"curricular"`
	Subjects     []string       `json:"subjects"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, createDocument,
		arg.Filename,
		arg.Title,
		arg.MimeType,
		arg.Content,
		arg.StoragePath,
		arg.RagStatus,
		arg.UserID,
		arg.SubjectID,
		arg.CurriculumID,
		arg.Curricular,
		pq.Array(arg.Subjects),
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Title,
		&i.MimeType,
		&i.Content,
		&i.StoragePath,
		&i.RagStatus,
		&i.UserID,
		&i.SubjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Curricular,
		pq.Array(&i.Subjects),
		&i.CurriculumID,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM documents WHERE id = $1
`

func (q *Queries) DeleteDocument(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDocument, id)
	return err
}

const getDocument = `-- name: GetDocument :one
SELECT id, filename, title, mime_type, content, storage_path, rag_status, user_id, subject_id, created_at, updated_at, curricular, subjects, curriculum_id FROM documents WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDocument(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Title,
		&i.MimeType,
		&i.Content,
		&i.StoragePath,
		&i.RagStatus,
		&i.UserID,
		&i.SubjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Curricular,
		pq.Array(&i.Subjects),
		&i.CurriculumID,
	)
	return i, err
}

const getDocumentsByCurriculum = `-- name: GetDocumentsByCurriculum :many
SELECT id, filename, title, mime_type, content, storage_path, rag_status, user_id, subject_id, created_at, updated_at, curricular, subjects, curriculum_id FROM documents
WHERE curriculum_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetDocumentsByCurriculum(ctx context.Context, curriculumID uuid.NullUUID) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, getDocumentsByCurriculum, curriculumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.Title,
			&i.MimeType,
			&i.Content,
			&i.StoragePath,
			&i.RagStatus,
			&i.UserID,
			&i.SubjectID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Curricular,
			pq.Array(&i.Subjects),
			&i.CurriculumID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocumentsByRagStatus = `-- name: GetDocumentsByRagStatus :many
SELECT id, filename, title, mime_type, content, storage_path, rag_status, user_id, subject_id, created_at, updated_at, curricular, subjects, curriculum_id FROM documents WHERE rag_status = $1 ORDER BY created_at DESC
`

func (q *Queries) GetDocumentsByRagStatus(ctx context.Context, ragStatus string) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, getDocumentsByRagStatus, ragStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.Title,
			&i.MimeType,
			&i.Content,
			&i.StoragePath,
			&i.RagStatus,
			&i.UserID,
			&i.SubjectID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Curricular,
			pq.Array(&i.Subjects),
			&i.CurriculumID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocumentsBySubject = `-- name: GetDocumentsBySubject :many
SELECT id, filename, title, mime_type, content, storage_path, rag_status, user_id, subject_id, created_at, updated_at, curricular, subjects, curriculum_id FROM documents WHERE subject_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetDocumentsBySubject(ctx context.Context, subjectID uuid.NullUUID) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, getDocumentsBySubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.Title,
			&i.MimeType,
			&i.Content,
			&i.StoragePath,
			&i.RagStatus,
			&i.UserID,
			&i.SubjectID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Curricular,
			pq.Array(&i.Subjects),
			&i.CurriculumID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocumentsBySubjects = `-- name: GetDocumentsBySubjects :many
SELECT id, filename, title, mime_type, content, storage_path, rag_status, user_id, subject_id, created_at, updated_at, curricular, subjects, curriculum_id FROM documents 
WHERE subjects && $1::text[]
ORDER BY created_at DESC
`

func (q *Queries) GetDocumentsBySubjects(ctx context.Context, dollar_1 []string) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, getDocumentsBySubjects, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.Title,
			&i.MimeType,
			&i.Content,
			&i.StoragePath,
			&i.RagStatus,
			&i.UserID,
			&i.SubjectID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Curricular,
			pq.Array(&i.Subjects),
			&i.CurriculumID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocumentsByUser = `-- name: GetDocumentsByUser :many
SELECT id, filename, title, mime_type, content, storage_path, rag_status, user_id, subject_id, created_at, updated_at, curricular, subjects, curriculum_id FROM documents WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetDocumentsByUser(ctx context.Context, userID uuid.UUID) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, getDocumentsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.Title,
			&i.MimeType,
			&i.Content,
			&i.StoragePath,
			&i.RagStatus,
			&i.UserID,
			&i.SubjectID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Curricular,
			pq.Array(&i.Subjects),
			&i.CurriculumID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, filename, title, mime_type, content, storage_path, rag_status, user_id, subject_id, created_at, updated_at, curricular, subjects, curriculum_id FROM documents ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListDocumentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocuments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.Title,
			&i.MimeType,
			&i.Content,
			&i.StoragePath,
			&i.RagStatus,
			&i.UserID,
			&i.SubjectID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Curricular,
			pq.Array(&i.Subjects),
			&i.CurriculumID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDocumentsByTitle = `-- name: SearchDocumentsByTitle :many
SELECT id, filename, title, mime_type, content, storage_path, rag_status, user_id, subject_id, created_at, updated_at, curricular, subjects, curriculum_id FROM documents 
WHERE title ILIKE '%' || $1 || '%' 
ORDER BY created_at DESC 
LIMIT $3 OFFSET $2
`

type SearchDocumentsByTitleParams struct {
	Title      sql.NullString `json:"title"`
	PageOffset int32          `json:"page_offset"`
	PageLimit  int32          `json:"page_limit"`
}

func (q *Queries) SearchDocumentsByTitle(ctx context.Context, arg SearchDocumentsByTitleParams) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, searchDocumentsByTitle, arg.Title, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.Title,
			&i.MimeType,
			&i.Content,
			&i.StoragePath,
			&i.RagStatus,
			&i.UserID,
			&i.SubjectID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Curricular,
			pq.Array(&i.Subjects),
			&i.CurriculumID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocument = `-- name: UpdateDocument :one
UPDATE documents SET
  title = COALESCE($2, title),
  content = COALESCE($3, content),
  storage_path = COALESCE($4, storage_path),
  rag_status = COALESCE($5, rag_status),
  subject_id = COALESCE($6, subject_id),
  curriculum_id = COALESCE($7, curriculum_id),
  curricular = COALESCE($8, curricular),
  subjects = COALESCE($9, subjects),
  updated_at = now()
WHERE id = $1
RETURNING id, filename, title, mime_type, content, storage_path, rag_status, user_id, subject_id, created_at, updated_at, curricular, subjects, curriculum_id
`

type UpdateDocumentParams struct {
	ID           uuid.UUID      `json:"id"`
	Title        sql.NullString `json:"title"`
	Content      sql.NullString `json:"content"`
	StoragePath  sql.NullString `json:"storage_path"`
	RagStatus    string         `json:"rag_status"`
	SubjectID    uuid.NullUUID  `json:"subject_id"`
	CurriculumID uuid.NullUUID  `json:"curriculum_id"`
	Curricular   sql.NullString `json:"curricular"`
	Subjects     []string       `json:"subjects"`
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, updateDocument,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.StoragePath,
		arg.RagStatus,
		arg.SubjectID,
		arg.CurriculumID,
		arg.Curricular,
		pq.Array(arg.Subjects),
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Title,
		&i.MimeType,
		&i.Content,
		&i.StoragePath,
		&i.RagStatus,
		&i.UserID,
		&i.SubjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Curricular,
		pq.Array(&i.Subjects),
		&i.CurriculumID,
	)
	return i, err
}

const updateDocumentRagStatus = `-- name: UpdateDocumentRagStatus :one
UPDATE documents SET
  rag_status = $2,
  updated_at = now()
WHERE id = $1
RETURNING id, filename, title, mime_type, content, storage_path, rag_status, user_id, subject_id, created_at, updated_at, curricular, subjects, curriculum_id
`

type UpdateDocumentRagStatusParams struct {
	ID        uuid.UUID `json:"id"`
	RagStatus string    `json:"rag_status"`
}

func (q *Queries) UpdateDocumentRagStatus(ctx context.Context, arg UpdateDocumentRagStatusParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, updateDocumentRagStatus, arg.ID, arg.RagStatus)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Title,
		&i.MimeType,
		&i.Content,
		&i.StoragePath,
		&i.RagStatus,
		&i.UserID,
		&i.SubjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Curricular,
		pq.Array(&i.Subjects),
		&i.CurriculumID,
	)
	return i, err
}
