// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Artifact struct {
	ID         uuid.UUID             `json:"id"`
	Type       string                `json:"type"`
	Status     string                `json:"status"`
	DocumentID uuid.NullUUID         `json:"document_id"`
	EvalID     uuid.NullUUID         `json:"eval_id"`
	EvalItemID uuid.NullUUID         `json:"eval_item_id"`
	AttemptID  uuid.NullUUID         `json:"attempt_id"`
	UserID     uuid.NullUUID         `json:"user_id"`
	Text       sql.NullString        `json:"text"`
	Json       pqtype.NullRawMessage `json:"json"`
	Model      sql.NullString        `json:"model"`
	Prompt     sql.NullString        `json:"prompt"`
	InputHash  sql.NullString        `json:"input_hash"`
	Meta       pqtype.NullRawMessage `json:"meta"`
	Error      sql.NullString        `json:"error"`
	CreatedAt  time.Time             `json:"created_at"`
}

type Document struct {
	ID          uuid.UUID      `json:"id"`
	Filename    string         `json:"filename"`
	Title       sql.NullString `json:"title"`
	MimeType    sql.NullString `json:"mime_type"`
	Content     sql.NullString `json:"content"`
	StoragePath sql.NullString `json:"storage_path"`
	RagStatus   string         `json:"rag_status"`
	UserID      uuid.UUID      `json:"user_id"`
	SubjectID   uuid.NullUUID  `json:"subject_id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	// Curricular classification or framework (e.g., Common Core, IB)
	Curricular sql.NullString `json:"curricular"`
	// List of academic subjects associated with this document
	Subjects []string `json:"subjects"`
}

type Eval struct {
	ID           uuid.UUID             `json:"id"`
	Title        string                `json:"title"`
	Description  sql.NullString        `json:"description"`
	Status       string                `json:"status"`
	Difficulty   sql.NullString        `json:"difficulty"`
	Instructions sql.NullString        `json:"instructions"`
	Rubric       pqtype.NullRawMessage `json:"rubric"`
	SubjectID    uuid.NullUUID         `json:"subject_id"`
	UserID       uuid.UUID             `json:"user_id"`
	PublishedAt  sql.NullTime          `json:"published_at"`
	ArchivedAt   sql.NullTime          `json:"archived_at"`
	CreatedAt    time.Time             `json:"created_at"`
	UpdatedAt    time.Time             `json:"updated_at"`
}

type EvalItem struct {
	ID          uuid.UUID             `json:"id"`
	EvalID      uuid.UUID             `json:"eval_id"`
	Prompt      string                `json:"prompt"`
	Options     []string              `json:"options"`
	CorrectIdx  int32                 `json:"correct_idx"`
	Hint        sql.NullString        `json:"hint"`
	Explanation sql.NullString        `json:"explanation"`
	Metadata    pqtype.NullRawMessage `json:"metadata"`
}

type EvalItemReview struct {
	ID         uuid.UUID      `json:"id"`
	EvalItemID uuid.UUID      `json:"eval_item_id"`
	ReviewerID uuid.UUID      `json:"reviewer_id"`
	Verdict    string         `json:"verdict"`
	Reasons    []string       `json:"reasons"`
	Comments   sql.NullString `json:"comments"`
	CreatedAt  time.Time      `json:"created_at"`
}

type PromptTemplate struct {
	ID          uuid.UUID             `json:"id"`
	Key         string                `json:"key"`
	Version     int32                 `json:"version"`
	IsActive    bool                  `json:"is_active"`
	Title       string                `json:"title"`
	Description sql.NullString        `json:"description"`
	Template    string                `json:"template"`
	Metadata    pqtype.NullRawMessage `json:"metadata"`
	CreatedBy   sql.NullString        `json:"created_by"`
	CreatedAt   time.Time             `json:"created_at"`
	UpdatedAt   time.Time             `json:"updated_at"`
}

type Subject struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	UserID      uuid.UUID      `json:"user_id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type TestAttempt struct {
	ID          uuid.UUID             `json:"id"`
	UserID      uuid.UUID             `json:"user_id"`
	EvalID      uuid.UUID             `json:"eval_id"`
	Score       int32                 `json:"score"`
	Total       int32                 `json:"total"`
	Percentage  sql.NullFloat64       `json:"percentage"`
	TotalTime   sql.NullInt32         `json:"total_time"`
	Feedback    pqtype.NullRawMessage `json:"feedback"`
	Summary     sql.NullString        `json:"summary"`
	StartedAt   time.Time             `json:"started_at"`
	CompletedAt sql.NullTime          `json:"completed_at"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	IsAdmin   bool      `json:"is_admin"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type UserAnswer struct {
	ID          uuid.UUID     `json:"id"`
	AttemptID   uuid.UUID     `json:"attempt_id"`
	EvalItemID  uuid.UUID     `json:"eval_item_id"`
	SelectedIdx int32         `json:"selected_idx"`
	IsCorrect   bool          `json:"is_correct"`
	TimeSpent   sql.NullInt32 `json:"time_spent"`
	HintsUsed   int32         `json:"hints_used"`
	CreatedAt   time.Time     `json:"created_at"`
}
