// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

// Types of artifacts that can be generated in the system
type ArtifactType string

const (
	ArtifactTypeINTENTS        ArtifactType = "INTENTS"
	ArtifactTypePLAN           ArtifactType = "PLAN"
	ArtifactTypeEVAL           ArtifactType = "EVAL"
	ArtifactTypeEVALITEM       ArtifactType = "EVAL_ITEM"
	ArtifactTypePROMPT         ArtifactType = "PROMPT"
	ArtifactTypePROMPTPOLICY   ArtifactType = "PROMPT_POLICY"
	ArtifactTypeQUALITYMETRICS ArtifactType = "QUALITY_METRICS"
	ArtifactTypeHINT           ArtifactType = "HINT"
	ArtifactTypeSUMMARY        ArtifactType = "SUMMARY"
	ArtifactTypeOUTLINE        ArtifactType = "OUTLINE"
	ArtifactTypeOTHER          ArtifactType = "OTHER"
)

func (e *ArtifactType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ArtifactType(s)
	case string:
		*e = ArtifactType(s)
	default:
		return fmt.Errorf("unsupported scan type for ArtifactType: %T", src)
	}
	return nil
}

type NullArtifactType struct {
	ArtifactType ArtifactType `json:"artifact_type"`
	Valid        bool         `json:"valid"` // Valid is true if ArtifactType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullArtifactType) Scan(value interface{}) error {
	if value == nil {
		ns.ArtifactType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ArtifactType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullArtifactType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ArtifactType), nil
}

// Possible verdicts for eval item reviews
type ReviewVerdict string

const (
	ReviewVerdictAPPROVED      ReviewVerdict = "APPROVED"
	ReviewVerdictREJECTED      ReviewVerdict = "REJECTED"
	ReviewVerdictNEEDSREVISION ReviewVerdict = "NEEDS_REVISION"
)

func (e *ReviewVerdict) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReviewVerdict(s)
	case string:
		*e = ReviewVerdict(s)
	default:
		return fmt.Errorf("unsupported scan type for ReviewVerdict: %T", src)
	}
	return nil
}

type NullReviewVerdict struct {
	ReviewVerdict ReviewVerdict `json:"review_verdict"`
	Valid         bool          `json:"valid"` // Valid is true if ReviewVerdict is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReviewVerdict) Scan(value interface{}) error {
	if value == nil {
		ns.ReviewVerdict, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReviewVerdict.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReviewVerdict) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReviewVerdict), nil
}

type Artifact struct {
	ID         uuid.UUID             `json:"id"`
	Type       string                `json:"type"`
	Status     string                `json:"status"`
	DocumentID uuid.NullUUID         `json:"document_id"`
	EvalID     uuid.NullUUID         `json:"eval_id"`
	EvalItemID uuid.NullUUID         `json:"eval_item_id"`
	AttemptID  uuid.NullUUID         `json:"attempt_id"`
	UserID     uuid.NullUUID         `json:"user_id"`
	Text       sql.NullString        `json:"text"`
	Json       pqtype.NullRawMessage `json:"json"`
	Model      sql.NullString        `json:"model"`
	Prompt     sql.NullString        `json:"prompt"`
	InputHash  sql.NullString        `json:"input_hash"`
	Meta       pqtype.NullRawMessage `json:"meta"`
	Error      sql.NullString        `json:"error"`
	CreatedAt  time.Time             `json:"created_at"`
	// When the artifact was last updated
	UpdatedAt time.Time `json:"updated_at"`
}

type Document struct {
	ID          uuid.UUID      `json:"id"`
	Filename    string         `json:"filename"`
	Title       sql.NullString `json:"title"`
	MimeType    sql.NullString `json:"mime_type"`
	Content     sql.NullString `json:"content"`
	StoragePath sql.NullString `json:"storage_path"`
	RagStatus   string         `json:"rag_status"`
	UserID      uuid.UUID      `json:"user_id"`
	SubjectID   uuid.NullUUID  `json:"subject_id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	// Curricular classification or framework (e.g., Common Core, IB)
	Curricular sql.NullString `json:"curricular"`
	// List of academic subjects associated with this document
	Subjects []string `json:"subjects"`
}

type Eval struct {
	ID           uuid.UUID             `json:"id"`
	Title        string                `json:"title"`
	Description  sql.NullString        `json:"description"`
	Status       string                `json:"status"`
	Difficulty   sql.NullString        `json:"difficulty"`
	Instructions sql.NullString        `json:"instructions"`
	Rubric       pqtype.NullRawMessage `json:"rubric"`
	SubjectID    uuid.NullUUID         `json:"subject_id"`
	UserID       uuid.UUID             `json:"user_id"`
	PublishedAt  sql.NullTime          `json:"published_at"`
	ArchivedAt   sql.NullTime          `json:"archived_at"`
	CreatedAt    time.Time             `json:"created_at"`
	UpdatedAt    time.Time             `json:"updated_at"`
}

type EvalItem struct {
	ID          uuid.UUID             `json:"id"`
	EvalID      uuid.UUID             `json:"eval_id"`
	Prompt      string                `json:"prompt"`
	Options     []string              `json:"options"`
	CorrectIdx  int32                 `json:"correct_idx"`
	Hint        sql.NullString        `json:"hint"`
	Explanation sql.NullString        `json:"explanation"`
	Metadata    pqtype.NullRawMessage `json:"metadata"`
	// When the eval item was created
	CreatedAt time.Time `json:"created_at"`
	// When the eval item was last updated
	UpdatedAt time.Time `json:"updated_at"`
}

type EvalItemReview struct {
	ID         uuid.UUID      `json:"id"`
	EvalItemID uuid.UUID      `json:"eval_item_id"`
	ReviewerID uuid.UUID      `json:"reviewer_id"`
	Verdict    ReviewVerdict  `json:"verdict"`
	Reasons    []string       `json:"reasons"`
	Comments   sql.NullString `json:"comments"`
	CreatedAt  time.Time      `json:"created_at"`
	// When the review was last updated
	UpdatedAt time.Time `json:"updated_at"`
}

type PromptTemplate struct {
	ID          uuid.UUID             `json:"id"`
	Key         string                `json:"key"`
	Version     int32                 `json:"version"`
	IsActive    bool                  `json:"is_active"`
	Title       string                `json:"title"`
	Description sql.NullString        `json:"description"`
	Template    string                `json:"template"`
	Metadata    pqtype.NullRawMessage `json:"metadata"`
	CreatedBy   sql.NullString        `json:"created_by"`
	CreatedAt   time.Time             `json:"created_at"`
	UpdatedAt   time.Time             `json:"updated_at"`
}

// User authentication sessions
type Session struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	// Unique session token for authentication
	Token string `json:"token"`
	// When the session expires
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Subject struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	UserID      uuid.UUID      `json:"user_id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type TestAttempt struct {
	ID          uuid.UUID             `json:"id"`
	UserID      uuid.UUID             `json:"user_id"`
	EvalID      uuid.UUID             `json:"eval_id"`
	Score       int32                 `json:"score"`
	Total       int32                 `json:"total"`
	Percentage  sql.NullFloat64       `json:"percentage"`
	TotalTime   sql.NullInt32         `json:"total_time"`
	Feedback    pqtype.NullRawMessage `json:"feedback"`
	Summary     sql.NullString        `json:"summary"`
	StartedAt   time.Time             `json:"started_at"`
	CompletedAt sql.NullTime          `json:"completed_at"`
}

type User struct {
	ID       uuid.UUID `json:"id"`
	Email    string    `json:"email"`
	Password string    `json:"password"`
	// True if the user has administrative privileges
	IsAdmin   bool      `json:"is_admin"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	// True if the user is a learner/student
	IsLearner bool `json:"is_learner"`
	// True if the user is a teacher/instructor
	IsTeacher bool `json:"is_teacher"`
}

type UserAnswer struct {
	ID          uuid.UUID     `json:"id"`
	AttemptID   uuid.UUID     `json:"attempt_id"`
	EvalItemID  uuid.UUID     `json:"eval_item_id"`
	SelectedIdx int32         `json:"selected_idx"`
	IsCorrect   bool          `json:"is_correct"`
	TimeSpent   sql.NullInt32 `json:"time_spent"`
	HintsUsed   int32         `json:"hints_used"`
	CreatedAt   time.Time     `json:"created_at"`
	// When the user answer was last updated
	UpdatedAt time.Time `json:"updated_at"`
}
