// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: model_configs.sql

package store

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const activateModelConfig = `-- name: ActivateModelConfig :exec
WITH activated AS (
  UPDATE model_configs SET is_active = true WHERE model_configs.id = $1
)
UPDATE model_configs SET is_active = false WHERE model_configs.id != $1
`

func (q *Queries) ActivateModelConfig(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, activateModelConfig, id)
	return err
}

const createModelConfig = `-- name: CreateModelConfig :one
WITH inserted AS (
  INSERT INTO model_configs (
    version, model_name, temperature, max_tokens, top_p, top_k, mime_type, is_active, created_by
  ) VALUES (
    (SELECT COALESCE(MAX(version), 0) + 1 FROM model_configs),
    $1, $2, $3, $4, $5, $6, $7, $8
  )
  RETURNING id, version, model_name, temperature, max_tokens, top_p, top_k, is_active, created_by, created_at, mime_type
),
deactivated AS (
  UPDATE model_configs SET
    is_active = false
  WHERE model_configs.id != (SELECT id FROM inserted)
    AND (SELECT is_active FROM inserted) = true
)
SELECT id, version, model_name, temperature, max_tokens, top_p, top_k, is_active, created_by, created_at, mime_type FROM inserted
`

type CreateModelConfigParams struct {
	ModelName   string          `json:"model_name"`
	Temperature sql.NullFloat64 `json:"temperature"`
	MaxTokens   sql.NullInt32   `json:"max_tokens"`
	TopP        sql.NullFloat64 `json:"top_p"`
	TopK        sql.NullFloat64 `json:"top_k"`
	MimeType    sql.NullString  `json:"mime_type"`
	IsActive    bool            `json:"is_active"`
	CreatedBy   uuid.UUID       `json:"created_by"`
}

type CreateModelConfigRow struct {
	ID          uuid.UUID       `json:"id"`
	Version     int32           `json:"version"`
	ModelName   string          `json:"model_name"`
	Temperature sql.NullFloat64 `json:"temperature"`
	MaxTokens   sql.NullInt32   `json:"max_tokens"`
	TopP        sql.NullFloat64 `json:"top_p"`
	TopK        sql.NullFloat64 `json:"top_k"`
	IsActive    bool            `json:"is_active"`
	CreatedBy   uuid.UUID       `json:"created_by"`
	CreatedAt   time.Time       `json:"created_at"`
	MimeType    sql.NullString  `json:"mime_type"`
}

func (q *Queries) CreateModelConfig(ctx context.Context, arg CreateModelConfigParams) (CreateModelConfigRow, error) {
	row := q.db.QueryRowContext(ctx, createModelConfig,
		arg.ModelName,
		arg.Temperature,
		arg.MaxTokens,
		arg.TopP,
		arg.TopK,
		arg.MimeType,
		arg.IsActive,
		arg.CreatedBy,
	)
	var i CreateModelConfigRow
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.ModelName,
		&i.Temperature,
		&i.MaxTokens,
		&i.TopP,
		&i.TopK,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.MimeType,
	)
	return i, err
}

const deactivateOtherModelConfigs = `-- name: DeactivateOtherModelConfigs :exec
UPDATE model_configs SET is_active = false WHERE id != $1
`

func (q *Queries) DeactivateOtherModelConfigs(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deactivateOtherModelConfigs, id)
	return err
}

const getActiveModelConfig = `-- name: GetActiveModelConfig :one
SELECT id, version, model_name, temperature, max_tokens, top_p, top_k, is_active, created_by, created_at, mime_type FROM model_configs WHERE is_active = true LIMIT 1
`

func (q *Queries) GetActiveModelConfig(ctx context.Context) (ModelConfig, error) {
	row := q.db.QueryRowContext(ctx, getActiveModelConfig)
	var i ModelConfig
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.ModelName,
		&i.Temperature,
		&i.MaxTokens,
		&i.TopP,
		&i.TopK,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.MimeType,
	)
	return i, err
}

const getModelConfig = `-- name: GetModelConfig :one
SELECT id, version, model_name, temperature, max_tokens, top_p, top_k, is_active, created_by, created_at, mime_type FROM model_configs WHERE id = $1 LIMIT 1
`

func (q *Queries) GetModelConfig(ctx context.Context, id uuid.UUID) (ModelConfig, error) {
	row := q.db.QueryRowContext(ctx, getModelConfig, id)
	var i ModelConfig
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.ModelName,
		&i.Temperature,
		&i.MaxTokens,
		&i.TopP,
		&i.TopK,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.MimeType,
	)
	return i, err
}

const listModelConfigs = `-- name: ListModelConfigs :many
SELECT id, version, model_name, temperature, max_tokens, top_p, top_k, is_active, created_by, created_at, mime_type FROM model_configs ORDER BY created_at DESC
`

func (q *Queries) ListModelConfigs(ctx context.Context) ([]ModelConfig, error) {
	rows, err := q.db.QueryContext(ctx, listModelConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModelConfig
	for rows.Next() {
		var i ModelConfig
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.ModelName,
			&i.Temperature,
			&i.MaxTokens,
			&i.TopP,
			&i.TopK,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.MimeType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
