// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prompt_templates.sql

package store

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const activatePromptTemplate = `-- name: ActivatePromptTemplate :one
WITH target AS (
  SELECT generation_type FROM prompt_templates WHERE prompt_templates.id = $1
),
deactivated AS (
  UPDATE prompt_templates SET
    is_active = false,
    updated_at = now()
  WHERE generation_type = (SELECT generation_type FROM target) AND id != $1
),
activated AS (
  UPDATE prompt_templates SET
    is_active = true,
    updated_at = now()
  WHERE id = $1
  RETURNING id, generation_type, version, is_active, title, description, template, metadata, created_by, created_at, updated_at
)
SELECT id, generation_type, version, is_active, title, description, template, metadata, created_by, created_at, updated_at FROM activated
`

type ActivatePromptTemplateRow struct {
	ID             uuid.UUID             `json:"id"`
	GenerationType GenerationType        `json:"generation_type"`
	Version        int32                 `json:"version"`
	IsActive       bool                  `json:"is_active"`
	Title          string                `json:"title"`
	Description    sql.NullString        `json:"description"`
	Template       string                `json:"template"`
	Metadata       pqtype.NullRawMessage `json:"metadata"`
	CreatedBy      sql.NullString        `json:"created_by"`
	CreatedAt      time.Time             `json:"created_at"`
	UpdatedAt      time.Time             `json:"updated_at"`
}

func (q *Queries) ActivatePromptTemplate(ctx context.Context, id uuid.UUID) (ActivatePromptTemplateRow, error) {
	row := q.db.QueryRowContext(ctx, activatePromptTemplate, id)
	var i ActivatePromptTemplateRow
	err := row.Scan(
		&i.ID,
		&i.GenerationType,
		&i.Version,
		&i.IsActive,
		&i.Title,
		&i.Description,
		&i.Template,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createNewVersion = `-- name: CreateNewVersion :one
WITH inserted AS (
  INSERT INTO prompt_templates (
    generation_type, version, is_active, title, description, template, metadata, created_by
  ) VALUES (
    $1, 
    (SELECT COALESCE(MAX(version), 0) + 1 FROM prompt_templates WHERE generation_type = $1),
    $2, $3, $4, $5, $6, $7
  )
  RETURNING id, generation_type, version, is_active, title, description, template, metadata, created_by, created_at, updated_at
),
deactivated AS (
  UPDATE prompt_templates SET
    is_active = false,
    updated_at = now()
  WHERE generation_type = (SELECT generation_type FROM inserted)
    AND id != (SELECT id FROM inserted)
    AND (SELECT is_active FROM inserted) = true
)
SELECT id, generation_type, version, is_active, title, description, template, metadata, created_by, created_at, updated_at FROM inserted
`

type CreateNewVersionParams struct {
	GenerationType GenerationType        `json:"generation_type"`
	IsActive       bool                  `json:"is_active"`
	Title          string                `json:"title"`
	Description    sql.NullString        `json:"description"`
	Template       string                `json:"template"`
	Metadata       pqtype.NullRawMessage `json:"metadata"`
	CreatedBy      sql.NullString        `json:"created_by"`
}

type CreateNewVersionRow struct {
	ID             uuid.UUID             `json:"id"`
	GenerationType GenerationType        `json:"generation_type"`
	Version        int32                 `json:"version"`
	IsActive       bool                  `json:"is_active"`
	Title          string                `json:"title"`
	Description    sql.NullString        `json:"description"`
	Template       string                `json:"template"`
	Metadata       pqtype.NullRawMessage `json:"metadata"`
	CreatedBy      sql.NullString        `json:"created_by"`
	CreatedAt      time.Time             `json:"created_at"`
	UpdatedAt      time.Time             `json:"updated_at"`
}

func (q *Queries) CreateNewVersion(ctx context.Context, arg CreateNewVersionParams) (CreateNewVersionRow, error) {
	row := q.db.QueryRowContext(ctx, createNewVersion,
		arg.GenerationType,
		arg.IsActive,
		arg.Title,
		arg.Description,
		arg.Template,
		arg.Metadata,
		arg.CreatedBy,
	)
	var i CreateNewVersionRow
	err := row.Scan(
		&i.ID,
		&i.GenerationType,
		&i.Version,
		&i.IsActive,
		&i.Title,
		&i.Description,
		&i.Template,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPromptTemplate = `-- name: CreatePromptTemplate :one
WITH inserted AS (
  INSERT INTO prompt_templates (
    generation_type, version, is_active, title, description, template, metadata, created_by
  ) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
  )
  RETURNING id, generation_type, version, is_active, title, description, template, metadata, created_by, created_at, updated_at
),
deactivated AS (
  UPDATE prompt_templates SET
    is_active = false,
    updated_at = now()
  WHERE generation_type = (SELECT generation_type FROM inserted)
    AND id != (SELECT id FROM inserted)
    AND (SELECT is_active FROM inserted) = true
)
SELECT id, generation_type, version, is_active, title, description, template, metadata, created_by, created_at, updated_at FROM inserted
`

type CreatePromptTemplateParams struct {
	GenerationType GenerationType        `json:"generation_type"`
	Version        int32                 `json:"version"`
	IsActive       bool                  `json:"is_active"`
	Title          string                `json:"title"`
	Description    sql.NullString        `json:"description"`
	Template       string                `json:"template"`
	Metadata       pqtype.NullRawMessage `json:"metadata"`
	CreatedBy      sql.NullString        `json:"created_by"`
}

type CreatePromptTemplateRow struct {
	ID             uuid.UUID             `json:"id"`
	GenerationType GenerationType        `json:"generation_type"`
	Version        int32                 `json:"version"`
	IsActive       bool                  `json:"is_active"`
	Title          string                `json:"title"`
	Description    sql.NullString        `json:"description"`
	Template       string                `json:"template"`
	Metadata       pqtype.NullRawMessage `json:"metadata"`
	CreatedBy      sql.NullString        `json:"created_by"`
	CreatedAt      time.Time             `json:"created_at"`
	UpdatedAt      time.Time             `json:"updated_at"`
}

func (q *Queries) CreatePromptTemplate(ctx context.Context, arg CreatePromptTemplateParams) (CreatePromptTemplateRow, error) {
	row := q.db.QueryRowContext(ctx, createPromptTemplate,
		arg.GenerationType,
		arg.Version,
		arg.IsActive,
		arg.Title,
		arg.Description,
		arg.Template,
		arg.Metadata,
		arg.CreatedBy,
	)
	var i CreatePromptTemplateRow
	err := row.Scan(
		&i.ID,
		&i.GenerationType,
		&i.Version,
		&i.IsActive,
		&i.Title,
		&i.Description,
		&i.Template,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateOtherVersions = `-- name: DeactivateOtherVersions :exec
UPDATE prompt_templates SET
  is_active = false,
  updated_at = now()
WHERE generation_type = $1 AND id != $2
`

type DeactivateOtherVersionsParams struct {
	GenerationType GenerationType `json:"generation_type"`
	ID             uuid.UUID      `json:"id"`
}

func (q *Queries) DeactivateOtherVersions(ctx context.Context, arg DeactivateOtherVersionsParams) error {
	_, err := q.db.ExecContext(ctx, deactivateOtherVersions, arg.GenerationType, arg.ID)
	return err
}

const deactivatePromptTemplate = `-- name: DeactivatePromptTemplate :one
UPDATE prompt_templates SET
  is_active = false,
  updated_at = now()
WHERE id = $1
RETURNING id, generation_type, version, is_active, title, description, template, metadata, created_by, created_at, updated_at
`

func (q *Queries) DeactivatePromptTemplate(ctx context.Context, id uuid.UUID) (PromptTemplate, error) {
	row := q.db.QueryRowContext(ctx, deactivatePromptTemplate, id)
	var i PromptTemplate
	err := row.Scan(
		&i.ID,
		&i.GenerationType,
		&i.Version,
		&i.IsActive,
		&i.Title,
		&i.Description,
		&i.Template,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActivePromptTemplates = `-- name: GetActivePromptTemplates :many
SELECT id, generation_type, version, is_active, title, description, template, metadata, created_by, created_at, updated_at FROM prompt_templates WHERE is_active = true ORDER BY generation_type ASC
`

func (q *Queries) GetActivePromptTemplates(ctx context.Context) ([]PromptTemplate, error) {
	rows, err := q.db.QueryContext(ctx, getActivePromptTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromptTemplate
	for rows.Next() {
		var i PromptTemplate
		if err := rows.Scan(
			&i.ID,
			&i.GenerationType,
			&i.Version,
			&i.IsActive,
			&i.Title,
			&i.Description,
			&i.Template,
			&i.Metadata,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestVersionByGenerationType = `-- name: GetLatestVersionByGenerationType :one
SELECT COALESCE(MAX(version), 0) as latest_version
FROM prompt_templates 
WHERE generation_type = $1
`

func (q *Queries) GetLatestVersionByGenerationType(ctx context.Context, generationType GenerationType) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getLatestVersionByGenerationType, generationType)
	var latest_version interface{}
	err := row.Scan(&latest_version)
	return latest_version, err
}

const getPromptTemplate = `-- name: GetPromptTemplate :one
SELECT id, generation_type, version, is_active, title, description, template, metadata, created_by, created_at, updated_at FROM prompt_templates WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPromptTemplate(ctx context.Context, id uuid.UUID) (PromptTemplate, error) {
	row := q.db.QueryRowContext(ctx, getPromptTemplate, id)
	var i PromptTemplate
	err := row.Scan(
		&i.ID,
		&i.GenerationType,
		&i.Version,
		&i.IsActive,
		&i.Title,
		&i.Description,
		&i.Template,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPromptTemplateByGenerationType = `-- name: GetPromptTemplateByGenerationType :one
SELECT id, generation_type, version, is_active, title, description, template, metadata, created_by, created_at, updated_at FROM prompt_templates WHERE generation_type = $1 AND is_active = true LIMIT 1
`

func (q *Queries) GetPromptTemplateByGenerationType(ctx context.Context, generationType GenerationType) (PromptTemplate, error) {
	row := q.db.QueryRowContext(ctx, getPromptTemplateByGenerationType, generationType)
	var i PromptTemplate
	err := row.Scan(
		&i.ID,
		&i.GenerationType,
		&i.Version,
		&i.IsActive,
		&i.Title,
		&i.Description,
		&i.Template,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPromptTemplateByGenerationTypeAndVersion = `-- name: GetPromptTemplateByGenerationTypeAndVersion :one
SELECT id, generation_type, version, is_active, title, description, template, metadata, created_by, created_at, updated_at FROM prompt_templates WHERE generation_type = $1 AND version = $2 LIMIT 1
`

type GetPromptTemplateByGenerationTypeAndVersionParams struct {
	GenerationType GenerationType `json:"generation_type"`
	Version        int32          `json:"version"`
}

func (q *Queries) GetPromptTemplateByGenerationTypeAndVersion(ctx context.Context, arg GetPromptTemplateByGenerationTypeAndVersionParams) (PromptTemplate, error) {
	row := q.db.QueryRowContext(ctx, getPromptTemplateByGenerationTypeAndVersion, arg.GenerationType, arg.Version)
	var i PromptTemplate
	err := row.Scan(
		&i.ID,
		&i.GenerationType,
		&i.Version,
		&i.IsActive,
		&i.Title,
		&i.Description,
		&i.Template,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPromptTemplateStats = `-- name: GetPromptTemplateStats :one
SELECT 
  COUNT(*) as total_templates,
  COUNT(DISTINCT generation_type) as unique_keys,
  COUNT(CASE WHEN is_active = true THEN 1 END) as active_templates,
  AVG(version) as avg_version
FROM prompt_templates
`

type GetPromptTemplateStatsRow struct {
	TotalTemplates  int64   `json:"total_templates"`
	UniqueKeys      int64   `json:"unique_keys"`
	ActiveTemplates int64   `json:"active_templates"`
	AvgVersion      float64 `json:"avg_version"`
}

func (q *Queries) GetPromptTemplateStats(ctx context.Context) (GetPromptTemplateStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getPromptTemplateStats)
	var i GetPromptTemplateStatsRow
	err := row.Scan(
		&i.TotalTemplates,
		&i.UniqueKeys,
		&i.ActiveTemplates,
		&i.AvgVersion,
	)
	return i, err
}

const getPromptTemplatesByCreator = `-- name: GetPromptTemplatesByCreator :many
SELECT id, generation_type, version, is_active, title, description, template, metadata, created_by, created_at, updated_at FROM prompt_templates 
WHERE created_by = $1 
ORDER BY created_at DESC 
LIMIT $2 OFFSET $3
`

type GetPromptTemplatesByCreatorParams struct {
	CreatedBy sql.NullString `json:"created_by"`
	Limit     int32          `json:"limit"`
	Offset    int32          `json:"offset"`
}

func (q *Queries) GetPromptTemplatesByCreator(ctx context.Context, arg GetPromptTemplatesByCreatorParams) ([]PromptTemplate, error) {
	rows, err := q.db.QueryContext(ctx, getPromptTemplatesByCreator, arg.CreatedBy, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromptTemplate
	for rows.Next() {
		var i PromptTemplate
		if err := rows.Scan(
			&i.ID,
			&i.GenerationType,
			&i.Version,
			&i.IsActive,
			&i.Title,
			&i.Description,
			&i.Template,
			&i.Metadata,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPromptTemplatesByGenerationType = `-- name: GetPromptTemplatesByGenerationType :many
SELECT id, generation_type, version, is_active, title, description, template, metadata, created_by, created_at, updated_at FROM prompt_templates WHERE generation_type = $1 ORDER BY version DESC
`

func (q *Queries) GetPromptTemplatesByGenerationType(ctx context.Context, generationType GenerationType) ([]PromptTemplate, error) {
	rows, err := q.db.QueryContext(ctx, getPromptTemplatesByGenerationType, generationType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromptTemplate
	for rows.Next() {
		var i PromptTemplate
		if err := rows.Scan(
			&i.ID,
			&i.GenerationType,
			&i.Version,
			&i.IsActive,
			&i.Title,
			&i.Description,
			&i.Template,
			&i.Metadata,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromptTemplates = `-- name: ListPromptTemplates :many
SELECT id, generation_type, version, is_active, title, description, template, metadata, created_by, created_at, updated_at FROM prompt_templates ORDER BY generation_type ASC, version DESC LIMIT $1 OFFSET $2
`

type ListPromptTemplatesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPromptTemplates(ctx context.Context, arg ListPromptTemplatesParams) ([]PromptTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listPromptTemplates, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromptTemplate
	for rows.Next() {
		var i PromptTemplate
		if err := rows.Scan(
			&i.ID,
			&i.GenerationType,
			&i.Version,
			&i.IsActive,
			&i.Title,
			&i.Description,
			&i.Template,
			&i.Metadata,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPromptTemplatesByTitle = `-- name: SearchPromptTemplatesByTitle :many
SELECT id, generation_type, version, is_active, title, description, template, metadata, created_by, created_at, updated_at FROM prompt_templates 
WHERE title ILIKE '%' || $1 || '%' 
ORDER BY generation_type ASC, version DESC 
LIMIT $2 OFFSET $3
`

type SearchPromptTemplatesByTitleParams struct {
	Column1 sql.NullString `json:"column_1"`
	Limit   int32          `json:"limit"`
	Offset  int32          `json:"offset"`
}

func (q *Queries) SearchPromptTemplatesByTitle(ctx context.Context, arg SearchPromptTemplatesByTitleParams) ([]PromptTemplate, error) {
	rows, err := q.db.QueryContext(ctx, searchPromptTemplatesByTitle, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromptTemplate
	for rows.Next() {
		var i PromptTemplate
		if err := rows.Scan(
			&i.ID,
			&i.GenerationType,
			&i.Version,
			&i.IsActive,
			&i.Title,
			&i.Description,
			&i.Template,
			&i.Metadata,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
