// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prompt_templates.sql

package store

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const activatePromptTemplate = `-- name: ActivatePromptTemplate :one
UPDATE prompt_templates SET
  is_active = true,
  updated_at = now()
WHERE id = $1
RETURNING id, key, version, is_active, title, description, template, metadata, created_by, created_at, updated_at
`

func (q *Queries) ActivatePromptTemplate(ctx context.Context, id uuid.UUID) (PromptTemplate, error) {
	row := q.db.QueryRowContext(ctx, activatePromptTemplate, id)
	var i PromptTemplate
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Version,
		&i.IsActive,
		&i.Title,
		&i.Description,
		&i.Template,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createNewVersion = `-- name: CreateNewVersion :one
INSERT INTO prompt_templates (
  key, version, is_active, title, description, template, metadata, created_by
) VALUES (
  $1, 
  (SELECT COALESCE(MAX(version), 0) + 1 FROM prompt_templates WHERE key = $1),
  $2, $3, $4, $5, $6, $7
) RETURNING id, key, version, is_active, title, description, template, metadata, created_by, created_at, updated_at
`

type CreateNewVersionParams struct {
	Key         string                `json:"key"`
	IsActive    bool                  `json:"is_active"`
	Title       string                `json:"title"`
	Description sql.NullString        `json:"description"`
	Template    string                `json:"template"`
	Metadata    pqtype.NullRawMessage `json:"metadata"`
	CreatedBy   sql.NullString        `json:"created_by"`
}

func (q *Queries) CreateNewVersion(ctx context.Context, arg CreateNewVersionParams) (PromptTemplate, error) {
	row := q.db.QueryRowContext(ctx, createNewVersion,
		arg.Key,
		arg.IsActive,
		arg.Title,
		arg.Description,
		arg.Template,
		arg.Metadata,
		arg.CreatedBy,
	)
	var i PromptTemplate
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Version,
		&i.IsActive,
		&i.Title,
		&i.Description,
		&i.Template,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPromptTemplate = `-- name: CreatePromptTemplate :one
INSERT INTO prompt_templates (
  key, version, is_active, title, description, template, metadata, created_by
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, key, version, is_active, title, description, template, metadata, created_by, created_at, updated_at
`

type CreatePromptTemplateParams struct {
	Key         string                `json:"key"`
	Version     int32                 `json:"version"`
	IsActive    bool                  `json:"is_active"`
	Title       string                `json:"title"`
	Description sql.NullString        `json:"description"`
	Template    string                `json:"template"`
	Metadata    pqtype.NullRawMessage `json:"metadata"`
	CreatedBy   sql.NullString        `json:"created_by"`
}

func (q *Queries) CreatePromptTemplate(ctx context.Context, arg CreatePromptTemplateParams) (PromptTemplate, error) {
	row := q.db.QueryRowContext(ctx, createPromptTemplate,
		arg.Key,
		arg.Version,
		arg.IsActive,
		arg.Title,
		arg.Description,
		arg.Template,
		arg.Metadata,
		arg.CreatedBy,
	)
	var i PromptTemplate
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Version,
		&i.IsActive,
		&i.Title,
		&i.Description,
		&i.Template,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateOtherVersions = `-- name: DeactivateOtherVersions :exec
UPDATE prompt_templates SET
  is_active = false,
  updated_at = now()
WHERE key = $1 AND id != $2
`

type DeactivateOtherVersionsParams struct {
	Key string    `json:"key"`
	ID  uuid.UUID `json:"id"`
}

func (q *Queries) DeactivateOtherVersions(ctx context.Context, arg DeactivateOtherVersionsParams) error {
	_, err := q.db.ExecContext(ctx, deactivateOtherVersions, arg.Key, arg.ID)
	return err
}

const deactivatePromptTemplate = `-- name: DeactivatePromptTemplate :one
UPDATE prompt_templates SET
  is_active = false,
  updated_at = now()
WHERE id = $1
RETURNING id, key, version, is_active, title, description, template, metadata, created_by, created_at, updated_at
`

func (q *Queries) DeactivatePromptTemplate(ctx context.Context, id uuid.UUID) (PromptTemplate, error) {
	row := q.db.QueryRowContext(ctx, deactivatePromptTemplate, id)
	var i PromptTemplate
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Version,
		&i.IsActive,
		&i.Title,
		&i.Description,
		&i.Template,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActivePromptTemplates = `-- name: GetActivePromptTemplates :many
SELECT id, key, version, is_active, title, description, template, metadata, created_by, created_at, updated_at FROM prompt_templates WHERE is_active = true ORDER BY key ASC
`

func (q *Queries) GetActivePromptTemplates(ctx context.Context) ([]PromptTemplate, error) {
	rows, err := q.db.QueryContext(ctx, getActivePromptTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromptTemplate
	for rows.Next() {
		var i PromptTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Version,
			&i.IsActive,
			&i.Title,
			&i.Description,
			&i.Template,
			&i.Metadata,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestVersionByKey = `-- name: GetLatestVersionByKey :one
SELECT COALESCE(MAX(version), 0) as latest_version
FROM prompt_templates 
WHERE key = $1
`

func (q *Queries) GetLatestVersionByKey(ctx context.Context, key string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getLatestVersionByKey, key)
	var latest_version interface{}
	err := row.Scan(&latest_version)
	return latest_version, err
}

const getPromptTemplate = `-- name: GetPromptTemplate :one
SELECT id, key, version, is_active, title, description, template, metadata, created_by, created_at, updated_at FROM prompt_templates WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPromptTemplate(ctx context.Context, id uuid.UUID) (PromptTemplate, error) {
	row := q.db.QueryRowContext(ctx, getPromptTemplate, id)
	var i PromptTemplate
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Version,
		&i.IsActive,
		&i.Title,
		&i.Description,
		&i.Template,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPromptTemplateByKey = `-- name: GetPromptTemplateByKey :one
SELECT id, key, version, is_active, title, description, template, metadata, created_by, created_at, updated_at FROM prompt_templates WHERE key = $1 AND is_active = true LIMIT 1
`

func (q *Queries) GetPromptTemplateByKey(ctx context.Context, key string) (PromptTemplate, error) {
	row := q.db.QueryRowContext(ctx, getPromptTemplateByKey, key)
	var i PromptTemplate
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Version,
		&i.IsActive,
		&i.Title,
		&i.Description,
		&i.Template,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPromptTemplateByKeyAndVersion = `-- name: GetPromptTemplateByKeyAndVersion :one
SELECT id, key, version, is_active, title, description, template, metadata, created_by, created_at, updated_at FROM prompt_templates WHERE key = $1 AND version = $2 LIMIT 1
`

type GetPromptTemplateByKeyAndVersionParams struct {
	Key     string `json:"key"`
	Version int32  `json:"version"`
}

func (q *Queries) GetPromptTemplateByKeyAndVersion(ctx context.Context, arg GetPromptTemplateByKeyAndVersionParams) (PromptTemplate, error) {
	row := q.db.QueryRowContext(ctx, getPromptTemplateByKeyAndVersion, arg.Key, arg.Version)
	var i PromptTemplate
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Version,
		&i.IsActive,
		&i.Title,
		&i.Description,
		&i.Template,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPromptTemplateStats = `-- name: GetPromptTemplateStats :one
SELECT 
  COUNT(*) as total_templates,
  COUNT(DISTINCT key) as unique_keys,
  COUNT(CASE WHEN is_active = true THEN 1 END) as active_templates,
  AVG(version) as avg_version
FROM prompt_templates
`

type GetPromptTemplateStatsRow struct {
	TotalTemplates  int64   `json:"total_templates"`
	UniqueKeys      int64   `json:"unique_keys"`
	ActiveTemplates int64   `json:"active_templates"`
	AvgVersion      float64 `json:"avg_version"`
}

func (q *Queries) GetPromptTemplateStats(ctx context.Context) (GetPromptTemplateStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getPromptTemplateStats)
	var i GetPromptTemplateStatsRow
	err := row.Scan(
		&i.TotalTemplates,
		&i.UniqueKeys,
		&i.ActiveTemplates,
		&i.AvgVersion,
	)
	return i, err
}

const getPromptTemplatesByCreator = `-- name: GetPromptTemplatesByCreator :many
SELECT id, key, version, is_active, title, description, template, metadata, created_by, created_at, updated_at FROM prompt_templates 
WHERE created_by = $1 
ORDER BY created_at DESC 
LIMIT $2 OFFSET $3
`

type GetPromptTemplatesByCreatorParams struct {
	CreatedBy sql.NullString `json:"created_by"`
	Limit     int32          `json:"limit"`
	Offset    int32          `json:"offset"`
}

func (q *Queries) GetPromptTemplatesByCreator(ctx context.Context, arg GetPromptTemplatesByCreatorParams) ([]PromptTemplate, error) {
	rows, err := q.db.QueryContext(ctx, getPromptTemplatesByCreator, arg.CreatedBy, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromptTemplate
	for rows.Next() {
		var i PromptTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Version,
			&i.IsActive,
			&i.Title,
			&i.Description,
			&i.Template,
			&i.Metadata,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPromptTemplatesByKey = `-- name: GetPromptTemplatesByKey :many
SELECT id, key, version, is_active, title, description, template, metadata, created_by, created_at, updated_at FROM prompt_templates WHERE key = $1 ORDER BY version DESC
`

func (q *Queries) GetPromptTemplatesByKey(ctx context.Context, key string) ([]PromptTemplate, error) {
	rows, err := q.db.QueryContext(ctx, getPromptTemplatesByKey, key)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromptTemplate
	for rows.Next() {
		var i PromptTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Version,
			&i.IsActive,
			&i.Title,
			&i.Description,
			&i.Template,
			&i.Metadata,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromptTemplates = `-- name: ListPromptTemplates :many
SELECT id, key, version, is_active, title, description, template, metadata, created_by, created_at, updated_at FROM prompt_templates ORDER BY key ASC, version DESC LIMIT $1 OFFSET $2
`

type ListPromptTemplatesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPromptTemplates(ctx context.Context, arg ListPromptTemplatesParams) ([]PromptTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listPromptTemplates, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromptTemplate
	for rows.Next() {
		var i PromptTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Version,
			&i.IsActive,
			&i.Title,
			&i.Description,
			&i.Template,
			&i.Metadata,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPromptTemplatesByTitle = `-- name: SearchPromptTemplatesByTitle :many
SELECT id, key, version, is_active, title, description, template, metadata, created_by, created_at, updated_at FROM prompt_templates 
WHERE title ILIKE '%' || $1 || '%' 
ORDER BY key ASC, version DESC 
LIMIT $2 OFFSET $3
`

type SearchPromptTemplatesByTitleParams struct {
	Column1 sql.NullString `json:"column_1"`
	Limit   int32          `json:"limit"`
	Offset  int32          `json:"offset"`
}

func (q *Queries) SearchPromptTemplatesByTitle(ctx context.Context, arg SearchPromptTemplatesByTitleParams) ([]PromptTemplate, error) {
	rows, err := q.db.QueryContext(ctx, searchPromptTemplatesByTitle, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromptTemplate
	for rows.Next() {
		var i PromptTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Version,
			&i.IsActive,
			&i.Title,
			&i.Description,
			&i.Template,
			&i.Metadata,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
