// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	ActivatePromptTemplate(ctx context.Context, id uuid.UUID) (PromptTemplate, error)
	ArchiveEval(ctx context.Context, id uuid.UUID) (Eval, error)
	CompleteTestAttempt(ctx context.Context, arg CompleteTestAttemptParams) (TestAttempt, error)
	CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error)
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error)
	CreateEval(ctx context.Context, arg CreateEvalParams) (Eval, error)
	CreateEvalItem(ctx context.Context, arg CreateEvalItemParams) (EvalItem, error)
	CreateEvalItemReview(ctx context.Context, arg CreateEvalItemReviewParams) (EvalItemReview, error)
	CreateNewVersion(ctx context.Context, arg CreateNewVersionParams) (PromptTemplate, error)
	CreatePromptTemplate(ctx context.Context, arg CreatePromptTemplateParams) (PromptTemplate, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSubject(ctx context.Context, arg CreateSubjectParams) (Subject, error)
	CreateTestAttempt(ctx context.Context, arg CreateTestAttemptParams) (TestAttempt, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserAnswer(ctx context.Context, arg CreateUserAnswerParams) (UserAnswer, error)
	DeactivateOtherVersions(ctx context.Context, arg DeactivateOtherVersionsParams) error
	DeactivatePromptTemplate(ctx context.Context, id uuid.UUID) (PromptTemplate, error)
	DeleteArtifact(ctx context.Context, id uuid.UUID) error
	DeleteDocument(ctx context.Context, id uuid.UUID) error
	DeleteEval(ctx context.Context, id uuid.UUID) error
	DeleteEvalItem(ctx context.Context, id uuid.UUID) error
	DeleteEvalItemReview(ctx context.Context, id uuid.UUID) error
	DeletePromptTemplate(ctx context.Context, id uuid.UUID) error
	DeleteSession(ctx context.Context, token string) error
	DeleteSubject(ctx context.Context, id uuid.UUID) error
	DeleteTestAttempt(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteUserAnswer(ctx context.Context, id uuid.UUID) error
	DeleteUserSessions(ctx context.Context, userID uuid.UUID) error
	GetActiveAttempts(ctx context.Context) ([]TestAttempt, error)
	GetActivePromptTemplates(ctx context.Context) ([]PromptTemplate, error)
	GetAnswerStatsForEvalItem(ctx context.Context, evalItemID uuid.UUID) (GetAnswerStatsForEvalItemRow, error)
	GetAnswersByUserAndEval(ctx context.Context, arg GetAnswersByUserAndEvalParams) ([]GetAnswersByUserAndEvalRow, error)
	GetArtifact(ctx context.Context, id uuid.UUID) (Artifact, error)
	GetArtifactStats(ctx context.Context) (GetArtifactStatsRow, error)
	GetArtifactsByAttempt(ctx context.Context, attemptID uuid.NullUUID) ([]Artifact, error)
	GetArtifactsByDocument(ctx context.Context, documentID uuid.NullUUID) ([]Artifact, error)
	GetArtifactsByEval(ctx context.Context, evalID uuid.NullUUID) ([]Artifact, error)
	GetArtifactsByEvalItem(ctx context.Context, evalItemID uuid.NullUUID) ([]Artifact, error)
	GetArtifactsByInputHash(ctx context.Context, inputHash sql.NullString) ([]Artifact, error)
	GetArtifactsByStatus(ctx context.Context, status string) ([]Artifact, error)
	GetArtifactsByType(ctx context.Context, type_ string) ([]Artifact, error)
	GetArtifactsByTypeAndEntity(ctx context.Context, arg GetArtifactsByTypeAndEntityParams) ([]Artifact, error)
	GetArtifactsByUser(ctx context.Context, userID uuid.NullUUID) ([]Artifact, error)
	GetCompletedAttempts(ctx context.Context) ([]TestAttempt, error)
	GetCorrectAnswersByAttempt(ctx context.Context, attemptID uuid.UUID) ([]UserAnswer, error)
	GetDocument(ctx context.Context, id uuid.UUID) (Document, error)
	GetDocumentsByRagStatus(ctx context.Context, ragStatus string) ([]Document, error)
	GetDocumentsBySubject(ctx context.Context, subjectID uuid.NullUUID) ([]Document, error)
	GetDocumentsBySubjects(ctx context.Context, dollar_1 []string) ([]Document, error)
	GetDocumentsByUser(ctx context.Context, userID uuid.UUID) ([]Document, error)
	GetDraftEvals(ctx context.Context) ([]Eval, error)
	GetEval(ctx context.Context, id uuid.UUID) (Eval, error)
	GetEvalItem(ctx context.Context, id uuid.UUID) (EvalItem, error)
	GetEvalItemReview(ctx context.Context, id uuid.UUID) (EvalItemReview, error)
	GetEvalItemWithReviews(ctx context.Context, id uuid.UUID) (GetEvalItemWithReviewsRow, error)
	GetEvalItemsByEval(ctx context.Context, evalID uuid.UUID) ([]EvalItem, error)
	GetEvalItemsWithAnswerStats(ctx context.Context, evalID uuid.UUID) ([]GetEvalItemsWithAnswerStatsRow, error)
	GetEvalTestStats(ctx context.Context, evalID uuid.UUID) (GetEvalTestStatsRow, error)
	GetEvalWithItemCount(ctx context.Context, id uuid.UUID) (GetEvalWithItemCountRow, error)
	GetEvalsByStatus(ctx context.Context, status string) ([]Eval, error)
	GetEvalsBySubject(ctx context.Context, subjectID uuid.NullUUID) ([]Eval, error)
	GetEvalsByUser(ctx context.Context, userID uuid.UUID) ([]Eval, error)
	GetEvalsWithItemCounts(ctx context.Context, userID uuid.UUID) ([]GetEvalsWithItemCountsRow, error)
	GetIncorrectAnswersByAttempt(ctx context.Context, attemptID uuid.UUID) ([]UserAnswer, error)
	GetLatestArtifactByTypeAndEntity(ctx context.Context, arg GetLatestArtifactByTypeAndEntityParams) (Artifact, error)
	GetLatestVersionByKey(ctx context.Context, key string) (interface{}, error)
	GetPendingReviewsForEval(ctx context.Context, evalID uuid.UUID) ([]EvalItem, error)
	GetPromptTemplate(ctx context.Context, id uuid.UUID) (PromptTemplate, error)
	GetPromptTemplateByKey(ctx context.Context, key string) (PromptTemplate, error)
	GetPromptTemplateByKeyAndVersion(ctx context.Context, arg GetPromptTemplateByKeyAndVersionParams) (PromptTemplate, error)
	GetPromptTemplateStats(ctx context.Context) (GetPromptTemplateStatsRow, error)
	GetPromptTemplatesByCreator(ctx context.Context, arg GetPromptTemplatesByCreatorParams) ([]PromptTemplate, error)
	GetPromptTemplatesByKey(ctx context.Context, key string) ([]PromptTemplate, error)
	GetPublishedEvals(ctx context.Context) ([]Eval, error)
	GetRandomEvalItems(ctx context.Context, arg GetRandomEvalItemsParams) ([]EvalItem, error)
	GetReviewStatsForEvalItem(ctx context.Context, evalItemID uuid.UUID) (GetReviewStatsForEvalItemRow, error)
	GetReviewStatsForReviewer(ctx context.Context, reviewerID uuid.UUID) (GetReviewStatsForReviewerRow, error)
	GetReviewsByEvalItem(ctx context.Context, evalItemID uuid.UUID) ([]EvalItemReview, error)
	GetReviewsByEvalItemAndReviewer(ctx context.Context, arg GetReviewsByEvalItemAndReviewerParams) (EvalItemReview, error)
	GetReviewsByReviewer(ctx context.Context, reviewerID uuid.UUID) ([]EvalItemReview, error)
	GetReviewsByVerdict(ctx context.Context, verdict ReviewVerdict) ([]EvalItemReview, error)
	GetReviewsWithEvalItemDetails(ctx context.Context, arg GetReviewsWithEvalItemDetailsParams) ([]GetReviewsWithEvalItemDetailsRow, error)
	GetSessionByToken(ctx context.Context, token string) (Session, error)
	GetSubject(ctx context.Context, id uuid.UUID) (Subject, error)
	GetTestAttempt(ctx context.Context, id uuid.UUID) (TestAttempt, error)
	GetTestAttemptWithAnswers(ctx context.Context, id uuid.UUID) (GetTestAttemptWithAnswersRow, error)
	GetTestAttemptsByEval(ctx context.Context, evalID uuid.UUID) ([]TestAttempt, error)
	GetTestAttemptsByUser(ctx context.Context, userID uuid.UUID) ([]TestAttempt, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserAnswer(ctx context.Context, id uuid.UUID) (UserAnswer, error)
	GetUserAnswerByAttemptAndItem(ctx context.Context, arg GetUserAnswerByAttemptAndItemParams) (UserAnswer, error)
	GetUserAnswerPatterns(ctx context.Context, evalItemID uuid.UUID) ([]GetUserAnswerPatternsRow, error)
	GetUserAnswersByAttempt(ctx context.Context, attemptID uuid.UUID) ([]UserAnswer, error)
	GetUserAnswersByEvalItem(ctx context.Context, evalItemID uuid.UUID) ([]UserAnswer, error)
	GetUserAttemptsByEval(ctx context.Context, arg GetUserAttemptsByEvalParams) ([]TestAttempt, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserTestStats(ctx context.Context, userID uuid.UUID) (GetUserTestStatsRow, error)
	ListArtifacts(ctx context.Context, arg ListArtifactsParams) ([]Artifact, error)
	ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]Document, error)
	ListEvalItemReviews(ctx context.Context, arg ListEvalItemReviewsParams) ([]EvalItemReview, error)
	ListEvalItems(ctx context.Context, arg ListEvalItemsParams) ([]EvalItem, error)
	ListEvals(ctx context.Context, arg ListEvalsParams) ([]Eval, error)
	ListPromptTemplates(ctx context.Context, arg ListPromptTemplatesParams) ([]PromptTemplate, error)
	ListSubjectsByUser(ctx context.Context, userID uuid.UUID) ([]Subject, error)
	ListTestAttempts(ctx context.Context, arg ListTestAttemptsParams) ([]TestAttempt, error)
	ListUserAnswers(ctx context.Context, arg ListUserAnswersParams) ([]UserAnswer, error)
	ListUsers(ctx context.Context) ([]User, error)
	PublishEval(ctx context.Context, id uuid.UUID) (Eval, error)
	SearchDocumentsByTitle(ctx context.Context, arg SearchDocumentsByTitleParams) ([]Document, error)
	SearchEvalItemsByPrompt(ctx context.Context, arg SearchEvalItemsByPromptParams) ([]EvalItem, error)
	SearchEvalsByTitle(ctx context.Context, arg SearchEvalsByTitleParams) ([]Eval, error)
	SearchPromptTemplatesByTitle(ctx context.Context, arg SearchPromptTemplatesByTitleParams) ([]PromptTemplate, error)
	UpdateArtifact(ctx context.Context, arg UpdateArtifactParams) (Artifact, error)
	UpdateArtifactStatus(ctx context.Context, arg UpdateArtifactStatusParams) (Artifact, error)
	UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error)
	UpdateDocumentRagStatus(ctx context.Context, arg UpdateDocumentRagStatusParams) (Document, error)
	UpdateEval(ctx context.Context, arg UpdateEvalParams) (Eval, error)
	UpdateEvalItem(ctx context.Context, arg UpdateEvalItemParams) (EvalItem, error)
	UpdateEvalItemReview(ctx context.Context, arg UpdateEvalItemReviewParams) (EvalItemReview, error)
	UpdatePromptTemplate(ctx context.Context, arg UpdatePromptTemplateParams) (PromptTemplate, error)
	UpdateSubject(ctx context.Context, arg UpdateSubjectParams) (Subject, error)
	UpdateTestAttemptScore(ctx context.Context, arg UpdateTestAttemptScoreParams) (TestAttempt, error)
	UpdateTestAttemptTime(ctx context.Context, arg UpdateTestAttemptTimeParams) (TestAttempt, error)
	UpdateUserAnswer(ctx context.Context, arg UpdateUserAnswerParams) (UserAnswer, error)
}

var _ Querier = (*Queries)(nil)
