// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateSubject(ctx context.Context, arg CreateSubjectParams) (Subject, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteSubject(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetSubject(ctx context.Context, id uuid.UUID) (Subject, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListSubjectsByUser(ctx context.Context, userID uuid.UUID) ([]Subject, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateSubject(ctx context.Context, arg UpdateSubjectParams) (Subject, error)
}

var _ Querier = (*Queries)(nil)
