// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subjects.sql

package store

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createSubject = `-- name: CreateSubject :one
INSERT INTO subjects (
  id, name, description, user_id
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, name, description, user_id, created_at, updated_at
`

type CreateSubjectParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	UserID      uuid.UUID      `json:"user_id"`
}

func (q *Queries) CreateSubject(ctx context.Context, arg CreateSubjectParams) (Subject, error) {
	row := q.db.QueryRowContext(ctx, createSubject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.UserID,
	)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSubject = `-- name: DeleteSubject :exec
DELETE FROM subjects
WHERE id = $1
`

func (q *Queries) DeleteSubject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSubject, id)
	return err
}

const getSubject = `-- name: GetSubject :one
SELECT id, name, description, user_id, created_at, updated_at FROM subjects
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSubject(ctx context.Context, id uuid.UUID) (Subject, error) {
	row := q.db.QueryRowContext(ctx, getSubject, id)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubjectsByUser = `-- name: ListSubjectsByUser :many
SELECT id, name, description, user_id, created_at, updated_at FROM subjects
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSubjectsByUser(ctx context.Context, userID uuid.UUID) ([]Subject, error) {
	rows, err := q.db.QueryContext(ctx, listSubjectsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subject
	for rows.Next() {
		var i Subject
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubject = `-- name: UpdateSubject :one
UPDATE subjects
SET name = $2,
    description = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, name, description, user_id, created_at, updated_at
`

type UpdateSubjectParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) UpdateSubject(ctx context.Context, arg UpdateSubjectParams) (Subject, error) {
	row := q.db.QueryRowContext(ctx, updateSubject, arg.ID, arg.Name, arg.Description)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
