// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system_instructions.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const activateSystemInstruction = `-- name: ActivateSystemInstruction :exec
UPDATE system_instructions SET is_active = true WHERE id = $1
`

func (q *Queries) ActivateSystemInstruction(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, activateSystemInstruction, id)
	return err
}

const createSystemInstruction = `-- name: CreateSystemInstruction :one
INSERT INTO system_instructions (
  version, text, is_active, created_by
) VALUES (
  (SELECT COALESCE(MAX(version), 0) + 1 FROM system_instructions),
  $1, $2, $3
) RETURNING id, version, text, is_active, created_by, created_at
`

type CreateSystemInstructionParams struct {
	Text      string    `json:"text"`
	IsActive  bool      `json:"is_active"`
	CreatedBy uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateSystemInstruction(ctx context.Context, arg CreateSystemInstructionParams) (SystemInstruction, error) {
	row := q.db.QueryRowContext(ctx, createSystemInstruction, arg.Text, arg.IsActive, arg.CreatedBy)
	var i SystemInstruction
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Text,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateOtherSystemInstructions = `-- name: DeactivateOtherSystemInstructions :exec
UPDATE system_instructions SET is_active = false WHERE id != $1
`

func (q *Queries) DeactivateOtherSystemInstructions(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deactivateOtherSystemInstructions, id)
	return err
}

const getActiveSystemInstruction = `-- name: GetActiveSystemInstruction :one
SELECT id, version, text, is_active, created_by, created_at FROM system_instructions WHERE is_active = true LIMIT 1
`

func (q *Queries) GetActiveSystemInstruction(ctx context.Context) (SystemInstruction, error) {
	row := q.db.QueryRowContext(ctx, getActiveSystemInstruction)
	var i SystemInstruction
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Text,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getSystemInstruction = `-- name: GetSystemInstruction :one
SELECT id, version, text, is_active, created_by, created_at FROM system_instructions WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSystemInstruction(ctx context.Context, id uuid.UUID) (SystemInstruction, error) {
	row := q.db.QueryRowContext(ctx, getSystemInstruction, id)
	var i SystemInstruction
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Text,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listSystemInstructions = `-- name: ListSystemInstructions :many
SELECT id, version, text, is_active, created_by, created_at FROM system_instructions ORDER BY created_at DESC
`

func (q *Queries) ListSystemInstructions(ctx context.Context) ([]SystemInstruction, error) {
	rows, err := q.db.QueryContext(ctx, listSystemInstructions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemInstruction
	for rows.Next() {
		var i SystemInstruction
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.Text,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
