// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: textbooks.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSubSubject = `-- name: CreateSubSubject :one
INSERT INTO sub_subjects (id, subject_id, name, url, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, subject_id, name, url, created_at, updated_at
`

type CreateSubSubjectParams struct {
	ID        uuid.UUID `json:"id"`
	SubjectID uuid.UUID `json:"subject_id"`
	Name      string    `json:"name"`
	Url       string    `json:"url"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateSubSubject(ctx context.Context, arg CreateSubSubjectParams) (SubSubject, error) {
	row := q.db.QueryRowContext(ctx, createSubSubject,
		arg.ID,
		arg.SubjectID,
		arg.Name,
		arg.Url,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i SubSubject
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Name,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSubject = `-- name: CreateSubject :one
INSERT INTO subjects (id, name, url, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, url, created_at, updated_at
`

type CreateSubjectParams struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Url       string    `json:"url"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateSubject(ctx context.Context, arg CreateSubjectParams) (Subject, error) {
	row := q.db.QueryRowContext(ctx, createSubject,
		arg.ID,
		arg.Name,
		arg.Url,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllSubjects = `-- name: DeleteAllSubjects :exec
DELETE FROM subjects
`

func (q *Queries) DeleteAllSubjects(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllSubjects)
	return err
}

const deleteSubject = `-- name: DeleteSubject :exec
DELETE FROM subjects
WHERE id = $1
`

func (q *Queries) DeleteSubject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSubject, id)
	return err
}

const getAllSubjects = `-- name: GetAllSubjects :many
SELECT id, name, url, created_at, updated_at
FROM subjects
ORDER BY name ASC
`

func (q *Queries) GetAllSubjects(ctx context.Context) ([]Subject, error) {
	rows, err := q.db.QueryContext(ctx, getAllSubjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subject
	for rows.Next() {
		var i Subject
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubSubjectsBySubjectID = `-- name: GetSubSubjectsBySubjectID :many
SELECT id, subject_id, name, url, created_at, updated_at
FROM sub_subjects
WHERE subject_id = $1
ORDER BY name ASC
`

func (q *Queries) GetSubSubjectsBySubjectID(ctx context.Context, subjectID uuid.UUID) ([]SubSubject, error) {
	rows, err := q.db.QueryContext(ctx, getSubSubjectsBySubjectID, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubSubject
	for rows.Next() {
		var i SubSubject
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.Name,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubjectByID = `-- name: GetSubjectByID :one
SELECT id, name, url, created_at, updated_at
FROM subjects
WHERE id = $1
`

func (q *Queries) GetSubjectByID(ctx context.Context, id uuid.UUID) (Subject, error) {
	row := q.db.QueryRowContext(ctx, getSubjectByID, id)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubjectByName = `-- name: GetSubjectByName :one
SELECT id, name, url, created_at, updated_at
FROM subjects
WHERE name = $1
`

func (q *Queries) GetSubjectByName(ctx context.Context, name string) (Subject, error) {
	row := q.db.QueryRowContext(ctx, getSubjectByName, name)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
