// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artifacts.sql

package store

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createArtifact = `-- name: CreateArtifact :one
INSERT INTO artifacts (module_id, generation_run_id, type, status, schema_version, difficulty, tags, artifact_payload, grounding, evidence_version)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, module_id, generation_run_id, type, status, schema_version, difficulty, tags, artifact_payload, grounding, evidence_version, approved_at, rejected_at, created_at
`

type CreateArtifactParams struct {
	ModuleID        uuid.UUID       `json:"module_id"`
	GenerationRunID uuid.UUID       `json:"generation_run_id"`
	Type            string          `json:"type"`
	Status          string          `json:"status"`
	SchemaVersion   string          `json:"schema_version"`
	Difficulty      sql.NullString  `json:"difficulty"`
	Tags            []string        `json:"tags"`
	ArtifactPayload json.RawMessage `json:"artifact_payload"`
	Grounding       json.RawMessage `json:"grounding"`
	EvidenceVersion sql.NullString  `json:"evidence_version"`
}

func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, createArtifact,
		arg.ModuleID,
		arg.GenerationRunID,
		arg.Type,
		arg.Status,
		arg.SchemaVersion,
		arg.Difficulty,
		pq.Array(arg.Tags),
		arg.ArtifactPayload,
		arg.Grounding,
		arg.EvidenceVersion,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.GenerationRunID,
		&i.Type,
		&i.Status,
		&i.SchemaVersion,
		&i.Difficulty,
		pq.Array(&i.Tags),
		&i.ArtifactPayload,
		&i.Grounding,
		&i.EvidenceVersion,
		&i.ApprovedAt,
		&i.RejectedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteArtifact = `-- name: DeleteArtifact :exec
DELETE FROM artifacts WHERE id = $1
`

func (q *Queries) DeleteArtifact(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteArtifact, id)
	return err
}

const getArtifact = `-- name: GetArtifact :one
SELECT id, module_id, generation_run_id, type, status, schema_version, difficulty, tags, artifact_payload, grounding, evidence_version, approved_at, rejected_at, created_at FROM artifacts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetArtifact(ctx context.Context, id uuid.UUID) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, getArtifact, id)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.GenerationRunID,
		&i.Type,
		&i.Status,
		&i.SchemaVersion,
		&i.Difficulty,
		pq.Array(&i.Tags),
		&i.ArtifactPayload,
		&i.Grounding,
		&i.EvidenceVersion,
		&i.ApprovedAt,
		&i.RejectedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listArtifactsByModule = `-- name: ListArtifactsByModule :many
SELECT id, module_id, generation_run_id, type, status, schema_version, difficulty, tags, artifact_payload, grounding, evidence_version, approved_at, rejected_at, created_at FROM artifacts
WHERE module_id = $1
`

func (q *Queries) ListArtifactsByModule(ctx context.Context, moduleID uuid.UUID) ([]Artifact, error) {
	rows, err := q.db.QueryContext(ctx, listArtifactsByModule, moduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.ModuleID,
			&i.GenerationRunID,
			&i.Type,
			&i.Status,
			&i.SchemaVersion,
			&i.Difficulty,
			pq.Array(&i.Tags),
			&i.ArtifactPayload,
			&i.Grounding,
			&i.EvidenceVersion,
			&i.ApprovedAt,
			&i.RejectedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactsByModuleAndStatus = `-- name: ListArtifactsByModuleAndStatus :many
SELECT id, module_id, generation_run_id, type, status, schema_version, difficulty, tags, artifact_payload, grounding, evidence_version, approved_at, rejected_at, created_at FROM artifacts
WHERE module_id = $1 AND status = $2
`

type ListArtifactsByModuleAndStatusParams struct {
	ModuleID uuid.UUID `json:"module_id"`
	Status   string    `json:"status"`
}

func (q *Queries) ListArtifactsByModuleAndStatus(ctx context.Context, arg ListArtifactsByModuleAndStatusParams) ([]Artifact, error) {
	rows, err := q.db.QueryContext(ctx, listArtifactsByModuleAndStatus, arg.ModuleID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.ModuleID,
			&i.GenerationRunID,
			&i.Type,
			&i.Status,
			&i.SchemaVersion,
			&i.Difficulty,
			pq.Array(&i.Tags),
			&i.ArtifactPayload,
			&i.Grounding,
			&i.EvidenceVersion,
			&i.ApprovedAt,
			&i.RejectedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactsByModuleAndType = `-- name: ListArtifactsByModuleAndType :many
SELECT id, module_id, generation_run_id, type, status, schema_version, difficulty, tags, artifact_payload, grounding, evidence_version, approved_at, rejected_at, created_at FROM artifacts
WHERE module_id = $1 AND type = $2
`

type ListArtifactsByModuleAndTypeParams struct {
	ModuleID uuid.UUID `json:"module_id"`
	Type     string    `json:"type"`
}

func (q *Queries) ListArtifactsByModuleAndType(ctx context.Context, arg ListArtifactsByModuleAndTypeParams) ([]Artifact, error) {
	rows, err := q.db.QueryContext(ctx, listArtifactsByModuleAndType, arg.ModuleID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.ModuleID,
			&i.GenerationRunID,
			&i.Type,
			&i.Status,
			&i.SchemaVersion,
			&i.Difficulty,
			pq.Array(&i.Tags),
			&i.ArtifactPayload,
			&i.Grounding,
			&i.EvidenceVersion,
			&i.ApprovedAt,
			&i.RejectedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArtifactStatus = `-- name: UpdateArtifactStatus :exec
UPDATE artifacts
SET status = $2, approved_at = $3, rejected_at = $4
WHERE id = $1
`

type UpdateArtifactStatusParams struct {
	ID         uuid.UUID    `json:"id"`
	Status     string       `json:"status"`
	ApprovedAt sql.NullTime `json:"approved_at"`
	RejectedAt sql.NullTime `json:"rejected_at"`
}

func (q *Queries) UpdateArtifactStatus(ctx context.Context, arg UpdateArtifactStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateArtifactStatus,
		arg.ID,
		arg.Status,
		arg.ApprovedAt,
		arg.RejectedAt,
	)
	return err
}
