// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attempts.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createAttempt = `-- name: CreateAttempt :one
INSERT INTO attempts (session_id, tenant_id, artifact_id, is_correct, user_answer)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, session_id, artifact_id, is_correct, user_answer, created_at
`

type CreateAttemptParams struct {
	SessionID  uuid.UUID             `json:"session_id"`
	TenantID   uuid.UUID             `json:"tenant_id"`
	ArtifactID uuid.UUID             `json:"artifact_id"`
	IsCorrect  bool                  `json:"is_correct"`
	UserAnswer pqtype.NullRawMessage `json:"user_answer"`
}

func (q *Queries) CreateAttempt(ctx context.Context, arg CreateAttemptParams) (Attempt, error) {
	row := q.db.QueryRowContext(ctx, createAttempt,
		arg.SessionID,
		arg.TenantID,
		arg.ArtifactID,
		arg.IsCorrect,
		arg.UserAnswer,
	)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SessionID,
		&i.ArtifactID,
		&i.IsCorrect,
		&i.UserAnswer,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAttempt = `-- name: DeleteAttempt :exec
DELETE FROM attempts
WHERE id = $1
`

func (q *Queries) DeleteAttempt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAttempt, id)
	return err
}

const getAttempt = `-- name: GetAttempt :one
SELECT id, tenant_id, session_id, artifact_id, is_correct, user_answer, created_at FROM attempts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAttempt(ctx context.Context, id uuid.UUID) (Attempt, error) {
	row := q.db.QueryRowContext(ctx, getAttempt, id)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SessionID,
		&i.ArtifactID,
		&i.IsCorrect,
		&i.UserAnswer,
		&i.CreatedAt,
	)
	return i, err
}

const listAttemptsBySession = `-- name: ListAttemptsBySession :many
SELECT id, tenant_id, session_id, artifact_id, is_correct, user_answer, created_at FROM attempts
WHERE session_id = $1
`

func (q *Queries) ListAttemptsBySession(ctx context.Context, sessionID uuid.UUID) ([]Attempt, error) {
	rows, err := q.db.QueryContext(ctx, listAttemptsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attempt
	for rows.Next() {
		var i Attempt
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SessionID,
			&i.ArtifactID,
			&i.IsCorrect,
			&i.UserAnswer,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttemptsByTenant = `-- name: ListAttemptsByTenant :many
SELECT id, tenant_id, session_id, artifact_id, is_correct, user_answer, created_at FROM attempts
WHERE tenant_id = $1
`

func (q *Queries) ListAttemptsByTenant(ctx context.Context, tenantID uuid.UUID) ([]Attempt, error) {
	rows, err := q.db.QueryContext(ctx, listAttemptsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attempt
	for rows.Next() {
		var i Attempt
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SessionID,
			&i.ArtifactID,
			&i.IsCorrect,
			&i.UserAnswer,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
