// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents.sql

package store

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (module_id, store_id, title, source_uri, sha256, metadata, file_name, doc_name)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, module_id, store_id, title, source_uri, sha256, metadata, file_name, doc_name, indexed_at, created_at
`

type CreateDocumentParams struct {
	ModuleID  uuid.UUID       `json:"module_id"`
	StoreID   uuid.UUID       `json:"store_id"`
	Title     sql.NullString  `json:"title"`
	SourceUri string          `json:"source_uri"`
	Sha256    sql.NullString  `json:"sha256"`
	Metadata  json.RawMessage `json:"metadata"`
	FileName  sql.NullString  `json:"file_name"`
	DocName   sql.NullString  `json:"doc_name"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, createDocument,
		arg.ModuleID,
		arg.StoreID,
		arg.Title,
		arg.SourceUri,
		arg.Sha256,
		arg.Metadata,
		arg.FileName,
		arg.DocName,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.StoreID,
		&i.Title,
		&i.SourceUri,
		&i.Sha256,
		&i.Metadata,
		&i.FileName,
		&i.DocName,
		&i.IndexedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM documents WHERE id = $1
`

func (q *Queries) DeleteDocument(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDocument, id)
	return err
}

const getDocument = `-- name: GetDocument :one
SELECT id, module_id, store_id, title, source_uri, sha256, metadata, file_name, doc_name, indexed_at, created_at FROM documents
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDocument(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.StoreID,
		&i.Title,
		&i.SourceUri,
		&i.Sha256,
		&i.Metadata,
		&i.FileName,
		&i.DocName,
		&i.IndexedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDocumentByModuleAndSourceURI = `-- name: GetDocumentByModuleAndSourceURI :one
SELECT id, module_id, store_id, title, source_uri, sha256, metadata, file_name, doc_name, indexed_at, created_at FROM documents
WHERE module_id = $1 AND source_uri = $2 LIMIT 1
`

type GetDocumentByModuleAndSourceURIParams struct {
	ModuleID  uuid.UUID `json:"module_id"`
	SourceUri string    `json:"source_uri"`
}

func (q *Queries) GetDocumentByModuleAndSourceURI(ctx context.Context, arg GetDocumentByModuleAndSourceURIParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocumentByModuleAndSourceURI, arg.ModuleID, arg.SourceUri)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.StoreID,
		&i.Title,
		&i.SourceUri,
		&i.Sha256,
		&i.Metadata,
		&i.FileName,
		&i.DocName,
		&i.IndexedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listDocumentsByModule = `-- name: ListDocumentsByModule :many
SELECT id, module_id, store_id, title, source_uri, sha256, metadata, file_name, doc_name, indexed_at, created_at FROM documents
WHERE module_id = $1
`

func (q *Queries) ListDocumentsByModule(ctx context.Context, moduleID uuid.UUID) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentsByModule, moduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.ModuleID,
			&i.StoreID,
			&i.Title,
			&i.SourceUri,
			&i.Sha256,
			&i.Metadata,
			&i.FileName,
			&i.DocName,
			&i.IndexedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocument = `-- name: UpdateDocument :exec
UPDATE documents SET title = $2, metadata = $3, indexed_at = $4 WHERE id = $1
`

type UpdateDocumentParams struct {
	ID        uuid.UUID       `json:"id"`
	Title     sql.NullString  `json:"title"`
	Metadata  json.RawMessage `json:"metadata"`
	IndexedAt sql.NullTime    `json:"indexed_at"`
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) error {
	_, err := q.db.ExecContext(ctx, updateDocument,
		arg.ID,
		arg.Title,
		arg.Metadata,
		arg.IndexedAt,
	)
	return err
}
