// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents.sql

package store

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (subject_id, store_id, title, source_uri, sha256, metadata, file_name, doc_name)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, store_id, title, source_uri, sha256, metadata, file_name, doc_name, indexed_at, created_at, subject_id
`

type CreateDocumentParams struct {
	SubjectID uuid.UUID       `json:"subject_id"`
	StoreID   uuid.UUID       `json:"store_id"`
	Title     sql.NullString  `json:"title"`
	SourceUri string          `json:"source_uri"`
	Sha256    sql.NullString  `json:"sha256"`
	Metadata  json.RawMessage `json:"metadata"`
	FileName  sql.NullString  `json:"file_name"`
	DocName   sql.NullString  `json:"doc_name"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, createDocument,
		arg.SubjectID,
		arg.StoreID,
		arg.Title,
		arg.SourceUri,
		arg.Sha256,
		arg.Metadata,
		arg.FileName,
		arg.DocName,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Title,
		&i.SourceUri,
		&i.Sha256,
		&i.Metadata,
		&i.FileName,
		&i.DocName,
		&i.IndexedAt,
		&i.CreatedAt,
		&i.SubjectID,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM documents WHERE id = $1
`

func (q *Queries) DeleteDocument(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDocument, id)
	return err
}

const getDocument = `-- name: GetDocument :one
SELECT id, store_id, title, source_uri, sha256, metadata, file_name, doc_name, indexed_at, created_at, subject_id FROM documents
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDocument(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Title,
		&i.SourceUri,
		&i.Sha256,
		&i.Metadata,
		&i.FileName,
		&i.DocName,
		&i.IndexedAt,
		&i.CreatedAt,
		&i.SubjectID,
	)
	return i, err
}

const getDocumentBySubjectAndSourceURI = `-- name: GetDocumentBySubjectAndSourceURI :one
SELECT id, store_id, title, source_uri, sha256, metadata, file_name, doc_name, indexed_at, created_at, subject_id FROM documents
WHERE subject_id = $1 AND source_uri = $2 LIMIT 1
`

type GetDocumentBySubjectAndSourceURIParams struct {
	SubjectID uuid.UUID `json:"subject_id"`
	SourceUri string    `json:"source_uri"`
}

func (q *Queries) GetDocumentBySubjectAndSourceURI(ctx context.Context, arg GetDocumentBySubjectAndSourceURIParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocumentBySubjectAndSourceURI, arg.SubjectID, arg.SourceUri)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Title,
		&i.SourceUri,
		&i.Sha256,
		&i.Metadata,
		&i.FileName,
		&i.DocName,
		&i.IndexedAt,
		&i.CreatedAt,
		&i.SubjectID,
	)
	return i, err
}

const listDocumentsBySubject = `-- name: ListDocumentsBySubject :many
SELECT id, store_id, title, source_uri, sha256, metadata, file_name, doc_name, indexed_at, created_at, subject_id FROM documents
WHERE subject_id = $1
`

func (q *Queries) ListDocumentsBySubject(ctx context.Context, subjectID uuid.UUID) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentsBySubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.Title,
			&i.SourceUri,
			&i.Sha256,
			&i.Metadata,
			&i.FileName,
			&i.DocName,
			&i.IndexedAt,
			&i.CreatedAt,
			&i.SubjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocument = `-- name: UpdateDocument :exec
UPDATE documents SET title = $2, metadata = $3, indexed_at = $4 WHERE id = $1
`

type UpdateDocumentParams struct {
	ID        uuid.UUID       `json:"id"`
	Title     sql.NullString  `json:"title"`
	Metadata  json.RawMessage `json:"metadata"`
	IndexedAt sql.NullTime    `json:"indexed_at"`
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) error {
	_, err := q.db.ExecContext(ctx, updateDocument,
		arg.ID,
		arg.Title,
		arg.Metadata,
		arg.IndexedAt,
	)
	return err
}
