// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: file_search_stores.sql

package store

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const createFileSearchStore = `-- name: CreateFileSearchStore :one
INSERT INTO file_search_stores (subject_id, store_name, display_name, chunking_config)
VALUES ($1, $2, $3, $4)
RETURNING id, store_name, display_name, chunking_config, created_at, subject_id
`

type CreateFileSearchStoreParams struct {
	SubjectID      uuid.UUID       `json:"subject_id"`
	StoreName      string          `json:"store_name"`
	DisplayName    sql.NullString  `json:"display_name"`
	ChunkingConfig json.RawMessage `json:"chunking_config"`
}

func (q *Queries) CreateFileSearchStore(ctx context.Context, arg CreateFileSearchStoreParams) (FileSearchStore, error) {
	row := q.db.QueryRowContext(ctx, createFileSearchStore,
		arg.SubjectID,
		arg.StoreName,
		arg.DisplayName,
		arg.ChunkingConfig,
	)
	var i FileSearchStore
	err := row.Scan(
		&i.ID,
		&i.StoreName,
		&i.DisplayName,
		&i.ChunkingConfig,
		&i.CreatedAt,
		&i.SubjectID,
	)
	return i, err
}

const deleteFileSearchStore = `-- name: DeleteFileSearchStore :exec
DELETE FROM file_search_stores WHERE id = $1
`

func (q *Queries) DeleteFileSearchStore(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteFileSearchStore, id)
	return err
}

const getFileSearchStore = `-- name: GetFileSearchStore :one
SELECT id, store_name, display_name, chunking_config, created_at, subject_id FROM file_search_stores
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetFileSearchStore(ctx context.Context, id uuid.UUID) (FileSearchStore, error) {
	row := q.db.QueryRowContext(ctx, getFileSearchStore, id)
	var i FileSearchStore
	err := row.Scan(
		&i.ID,
		&i.StoreName,
		&i.DisplayName,
		&i.ChunkingConfig,
		&i.CreatedAt,
		&i.SubjectID,
	)
	return i, err
}

const getFileSearchStoreBySubjectID = `-- name: GetFileSearchStoreBySubjectID :one
SELECT id, store_name, display_name, chunking_config, created_at, subject_id FROM file_search_stores
WHERE subject_id = $1 LIMIT 1
`

func (q *Queries) GetFileSearchStoreBySubjectID(ctx context.Context, subjectID uuid.UUID) (FileSearchStore, error) {
	row := q.db.QueryRowContext(ctx, getFileSearchStoreBySubjectID, subjectID)
	var i FileSearchStore
	err := row.Scan(
		&i.ID,
		&i.StoreName,
		&i.DisplayName,
		&i.ChunkingConfig,
		&i.CreatedAt,
		&i.SubjectID,
	)
	return i, err
}

const updateFileSearchStore = `-- name: UpdateFileSearchStore :one
UPDATE file_search_stores
SET display_name = $2,
    chunking_config = $3
WHERE id = $1
RETURNING id, store_name, display_name, chunking_config, created_at, subject_id
`

type UpdateFileSearchStoreParams struct {
	ID             uuid.UUID       `json:"id"`
	DisplayName    sql.NullString  `json:"display_name"`
	ChunkingConfig json.RawMessage `json:"chunking_config"`
}

func (q *Queries) UpdateFileSearchStore(ctx context.Context, arg UpdateFileSearchStoreParams) (FileSearchStore, error) {
	row := q.db.QueryRowContext(ctx, updateFileSearchStore, arg.ID, arg.DisplayName, arg.ChunkingConfig)
	var i FileSearchStore
	err := row.Scan(
		&i.ID,
		&i.StoreName,
		&i.DisplayName,
		&i.ChunkingConfig,
		&i.CreatedAt,
		&i.SubjectID,
	)
	return i, err
}
