// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: generation_runs.sql

package store

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createGenerationRun = `-- name: CreateGenerationRun :one
INSERT INTO generation_runs (module_id, agent_name, agent_version, model, model_params, prompt_id, store_name, metadata_filter, status, input_payload)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, module_id, agent_name, agent_version, model, model_params, prompt_id, store_name, metadata_filter, status, input_payload, output_payload, error, started_at, finished_at, created_at
`

type CreateGenerationRunParams struct {
	ModuleID       uuid.UUID       `json:"module_id"`
	AgentName      string          `json:"agent_name"`
	AgentVersion   string          `json:"agent_version"`
	Model          string          `json:"model"`
	ModelParams    json.RawMessage `json:"model_params"`
	PromptID       uuid.NullUUID   `json:"prompt_id"`
	StoreName      string          `json:"store_name"`
	MetadataFilter json.RawMessage `json:"metadata_filter"`
	Status         string          `json:"status"`
	InputPayload   json.RawMessage `json:"input_payload"`
}

func (q *Queries) CreateGenerationRun(ctx context.Context, arg CreateGenerationRunParams) (GenerationRun, error) {
	row := q.db.QueryRowContext(ctx, createGenerationRun,
		arg.ModuleID,
		arg.AgentName,
		arg.AgentVersion,
		arg.Model,
		arg.ModelParams,
		arg.PromptID,
		arg.StoreName,
		arg.MetadataFilter,
		arg.Status,
		arg.InputPayload,
	)
	var i GenerationRun
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.AgentName,
		&i.AgentVersion,
		&i.Model,
		&i.ModelParams,
		&i.PromptID,
		&i.StoreName,
		&i.MetadataFilter,
		&i.Status,
		&i.InputPayload,
		&i.OutputPayload,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGenerationRun = `-- name: DeleteGenerationRun :exec
DELETE FROM generation_runs WHERE id = $1
`

func (q *Queries) DeleteGenerationRun(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteGenerationRun, id)
	return err
}

const getGenerationRun = `-- name: GetGenerationRun :one
SELECT id, module_id, agent_name, agent_version, model, model_params, prompt_id, store_name, metadata_filter, status, input_payload, output_payload, error, started_at, finished_at, created_at FROM generation_runs
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetGenerationRun(ctx context.Context, id uuid.UUID) (GenerationRun, error) {
	row := q.db.QueryRowContext(ctx, getGenerationRun, id)
	var i GenerationRun
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.AgentName,
		&i.AgentVersion,
		&i.Model,
		&i.ModelParams,
		&i.PromptID,
		&i.StoreName,
		&i.MetadataFilter,
		&i.Status,
		&i.InputPayload,
		&i.OutputPayload,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listGenerationRunsByModule = `-- name: ListGenerationRunsByModule :many
SELECT id, module_id, agent_name, agent_version, model, model_params, prompt_id, store_name, metadata_filter, status, input_payload, output_payload, error, started_at, finished_at, created_at FROM generation_runs
WHERE module_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListGenerationRunsByModule(ctx context.Context, moduleID uuid.UUID) ([]GenerationRun, error) {
	rows, err := q.db.QueryContext(ctx, listGenerationRunsByModule, moduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GenerationRun
	for rows.Next() {
		var i GenerationRun
		if err := rows.Scan(
			&i.ID,
			&i.ModuleID,
			&i.AgentName,
			&i.AgentVersion,
			&i.Model,
			&i.ModelParams,
			&i.PromptID,
			&i.StoreName,
			&i.MetadataFilter,
			&i.Status,
			&i.InputPayload,
			&i.OutputPayload,
			&i.Error,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGenerationRunsByStatus = `-- name: ListGenerationRunsByStatus :many
SELECT id, module_id, agent_name, agent_version, model, model_params, prompt_id, store_name, metadata_filter, status, input_payload, output_payload, error, started_at, finished_at, created_at FROM generation_runs
WHERE module_id = $1 AND status = $2
ORDER BY created_at DESC
`

type ListGenerationRunsByStatusParams struct {
	ModuleID uuid.UUID `json:"module_id"`
	Status   string    `json:"status"`
}

func (q *Queries) ListGenerationRunsByStatus(ctx context.Context, arg ListGenerationRunsByStatusParams) ([]GenerationRun, error) {
	rows, err := q.db.QueryContext(ctx, listGenerationRunsByStatus, arg.ModuleID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GenerationRun
	for rows.Next() {
		var i GenerationRun
		if err := rows.Scan(
			&i.ID,
			&i.ModuleID,
			&i.AgentName,
			&i.AgentVersion,
			&i.Model,
			&i.ModelParams,
			&i.PromptID,
			&i.StoreName,
			&i.MetadataFilter,
			&i.Status,
			&i.InputPayload,
			&i.OutputPayload,
			&i.Error,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGenerationRun = `-- name: UpdateGenerationRun :exec
UPDATE generation_runs
SET status = $2, output_payload = $3, error = $4, started_at = $5, finished_at = $6
WHERE id = $1
`

type UpdateGenerationRunParams struct {
	ID            uuid.UUID             `json:"id"`
	Status        string                `json:"status"`
	OutputPayload pqtype.NullRawMessage `json:"output_payload"`
	Error         pqtype.NullRawMessage `json:"error"`
	StartedAt     sql.NullTime          `json:"started_at"`
	FinishedAt    sql.NullTime          `json:"finished_at"`
}

func (q *Queries) UpdateGenerationRun(ctx context.Context, arg UpdateGenerationRunParams) error {
	_, err := q.db.ExecContext(ctx, updateGenerationRun,
		arg.ID,
		arg.Status,
		arg.OutputPayload,
		arg.Error,
		arg.StartedAt,
		arg.FinishedAt,
	)
	return err
}
