// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Artifact struct {
	ID              uuid.UUID       `json:"id"`
	ModuleID        uuid.UUID       `json:"module_id"`
	GenerationRunID uuid.UUID       `json:"generation_run_id"`
	Type            string          `json:"type"`
	Status          string          `json:"status"`
	SchemaVersion   string          `json:"schema_version"`
	Difficulty      sql.NullString  `json:"difficulty"`
	Tags            []string        `json:"tags"`
	ArtifactPayload json.RawMessage `json:"artifact_payload"`
	Grounding       json.RawMessage `json:"grounding"`
	EvidenceVersion sql.NullString  `json:"evidence_version"`
	ApprovedAt      sql.NullTime    `json:"approved_at"`
	RejectedAt      sql.NullTime    `json:"rejected_at"`
	CreatedAt       time.Time       `json:"created_at"`
}

type Attempt struct {
	ID         uuid.UUID             `json:"id"`
	TenantID   uuid.UUID             `json:"tenant_id"`
	SessionID  uuid.UUID             `json:"session_id"`
	ArtifactID uuid.UUID             `json:"artifact_id"`
	IsCorrect  bool                  `json:"is_correct"`
	UserAnswer pqtype.NullRawMessage `json:"user_answer"`
	CreatedAt  time.Time             `json:"created_at"`
}

type Document struct {
	ID        uuid.UUID       `json:"id"`
	StoreID   uuid.UUID       `json:"store_id"`
	Title     sql.NullString  `json:"title"`
	SourceUri string          `json:"source_uri"`
	Sha256    sql.NullString  `json:"sha256"`
	Metadata  json.RawMessage `json:"metadata"`
	FileName  sql.NullString  `json:"file_name"`
	DocName   sql.NullString  `json:"doc_name"`
	IndexedAt sql.NullTime    `json:"indexed_at"`
	CreatedAt time.Time       `json:"created_at"`
	SubjectID uuid.UUID       `json:"subject_id"`
}

type EvalResult struct {
	ID        uuid.UUID       `json:"id"`
	EvalRunID uuid.UUID       `json:"eval_run_id"`
	Pass      bool            `json:"pass"`
	Score     sql.NullFloat64 `json:"score"`
	Details   json.RawMessage `json:"details"`
	CreatedAt time.Time       `json:"created_at"`
	RuleID    uuid.UUID       `json:"rule_id"`
}

type EvalRule struct {
	ID        uuid.UUID       `json:"id"`
	SuiteID   uuid.UUID       `json:"suite_id"`
	EvalType  string          `json:"eval_type"`
	MinScore  sql.NullFloat64 `json:"min_score"`
	MaxScore  sql.NullFloat64 `json:"max_score"`
	Weight    float32         `json:"weight"`
	HardFail  bool            `json:"hard_fail"`
	Params    json.RawMessage `json:"params"`
	CreatedAt time.Time       `json:"created_at"`
}

type EvalRun struct {
	ID              uuid.UUID             `json:"id"`
	ArtifactID      uuid.UUID             `json:"artifact_id"`
	GenerationRunID uuid.NullUUID         `json:"generation_run_id"`
	SuiteID         uuid.UUID             `json:"suite_id"`
	JudgeModel      string                `json:"judge_model"`
	JudgeParams     json.RawMessage       `json:"judge_params"`
	Status          string                `json:"status"`
	OverallPass     sql.NullBool          `json:"overall_pass"`
	OverallScore    sql.NullFloat64       `json:"overall_score"`
	Error           pqtype.NullRawMessage `json:"error"`
	StartedAt       sql.NullTime          `json:"started_at"`
	FinishedAt      sql.NullTime          `json:"finished_at"`
	CreatedAt       time.Time             `json:"created_at"`
}

type EvalSuite struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	CreatedAt   time.Time `json:"created_at"`
	Description string    `json:"description"`
}

type FileSearchStore struct {
	ID             uuid.UUID       `json:"id"`
	StoreName      string          `json:"store_name"`
	DisplayName    sql.NullString  `json:"display_name"`
	ChunkingConfig json.RawMessage `json:"chunking_config"`
	CreatedAt      time.Time       `json:"created_at"`
	SubjectID      uuid.UUID       `json:"subject_id"`
}

type GenerationRun struct {
	ID             uuid.UUID             `json:"id"`
	ModuleID       uuid.UUID             `json:"module_id"`
	AgentName      string                `json:"agent_name"`
	AgentVersion   string                `json:"agent_version"`
	Model          string                `json:"model"`
	ModelParams    json.RawMessage       `json:"model_params"`
	PromptID       uuid.NullUUID         `json:"prompt_id"`
	StoreName      string                `json:"store_name"`
	MetadataFilter json.RawMessage       `json:"metadata_filter"`
	Status         string                `json:"status"`
	InputPayload   json.RawMessage       `json:"input_payload"`
	OutputPayload  pqtype.NullRawMessage `json:"output_payload"`
	Error          pqtype.NullRawMessage `json:"error"`
	StartedAt      sql.NullTime          `json:"started_at"`
	FinishedAt     sql.NullTime          `json:"finished_at"`
	CreatedAt      time.Time             `json:"created_at"`
}

type Module struct {
	ID          uuid.UUID      `json:"id"`
	TenantID    uuid.UUID      `json:"tenant_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
	Name        sql.NullString `json:"name"`
}

type PromptVersion struct {
	ID        uuid.UUID       `json:"id"`
	Name      string          `json:"name"`
	Version   string          `json:"version"`
	Content   string          `json:"content"`
	Metadata  json.RawMessage `json:"metadata"`
	CreatedAt time.Time       `json:"created_at"`
}

type Session struct {
	ID           uuid.UUID       `json:"id"`
	TenantID     uuid.UUID       `json:"tenant_id"`
	UserID       uuid.UUID       `json:"user_id"`
	ModuleID     uuid.UUID       `json:"module_id"`
	Status       string          `json:"status"`
	MasteryState json.RawMessage `json:"mastery_state"`
	CreatedAt    time.Time       `json:"created_at"`
	CompletedAt  sql.NullTime    `json:"completed_at"`
}

type Subject struct {
	ID          uuid.UUID      `json:"id"`
	UserID      uuid.UUID      `json:"user_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
}

type Tenant struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID          uuid.UUID      `json:"id"`
	TenantID    uuid.UUID      `json:"tenant_id"`
	Email       string         `json:"email"`
	DisplayName sql.NullString `json:"display_name"`
	IsActive    bool           `json:"is_active"`
	CreatedAt   time.Time      `json:"created_at"`
}

type UserRole struct {
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
	GrantedAt time.Time `json:"granted_at"`
}
