// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: modules.sql

package store

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createModule = `-- name: CreateModule :one
INSERT INTO modules (tenant_id, title, name, description)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, title, description, created_at, name
`

type CreateModuleParams struct {
	TenantID    uuid.UUID      `json:"tenant_id"`
	Title       string         `json:"title"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateModule(ctx context.Context, arg CreateModuleParams) (Module, error) {
	row := q.db.QueryRowContext(ctx, createModule,
		arg.TenantID,
		arg.Title,
		arg.Name,
		arg.Description,
	)
	var i Module
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.Name,
	)
	return i, err
}

const deleteModule = `-- name: DeleteModule :exec
DELETE FROM modules WHERE id = $1
`

func (q *Queries) DeleteModule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteModule, id)
	return err
}

const getModule = `-- name: GetModule :one
SELECT id, tenant_id, title, description, created_at, name FROM modules
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetModule(ctx context.Context, id uuid.UUID) (Module, error) {
	row := q.db.QueryRowContext(ctx, getModule, id)
	var i Module
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.Name,
	)
	return i, err
}

const getModuleByName = `-- name: GetModuleByName :one
SELECT id, tenant_id, title, description, created_at, name FROM modules
WHERE tenant_id = $1 AND name = $2 LIMIT 1
`

type GetModuleByNameParams struct {
	TenantID uuid.UUID      `json:"tenant_id"`
	Name     sql.NullString `json:"name"`
}

func (q *Queries) GetModuleByName(ctx context.Context, arg GetModuleByNameParams) (Module, error) {
	row := q.db.QueryRowContext(ctx, getModuleByName, arg.TenantID, arg.Name)
	var i Module
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.Name,
	)
	return i, err
}

const listModulesByTenant = `-- name: ListModulesByTenant :many
SELECT id, tenant_id, title, description, created_at, name FROM modules
WHERE tenant_id = $1
`

func (q *Queries) ListModulesByTenant(ctx context.Context, tenantID uuid.UUID) ([]Module, error) {
	rows, err := q.db.QueryContext(ctx, listModulesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Module
	for rows.Next() {
		var i Module
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateModule = `-- name: UpdateModule :exec
UPDATE modules SET name = $2, description = $3 WHERE id = $1
`

type UpdateModuleParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) UpdateModule(ctx context.Context, arg UpdateModuleParams) error {
	_, err := q.db.ExecContext(ctx, updateModule, arg.ID, arg.Name, arg.Description)
	return err
}
