// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error)
	CreateAttempt(ctx context.Context, arg CreateAttemptParams) (Attempt, error)
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error)
	CreateEvalRule(ctx context.Context, arg CreateEvalRuleParams) (EvalRule, error)
	CreateEvalRun(ctx context.Context, arg CreateEvalRunParams) (EvalRun, error)
	CreateEvalSuite(ctx context.Context, arg CreateEvalSuiteParams) (EvalSuite, error)
	CreateGenerationRun(ctx context.Context, arg CreateGenerationRunParams) (GenerationRun, error)
	CreateModule(ctx context.Context, arg CreateModuleParams) (Module, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserRole(ctx context.Context, arg CreateUserRoleParams) error
	DeleteArtifact(ctx context.Context, id uuid.UUID) error
	DeleteAttempt(ctx context.Context, id uuid.UUID) error
	DeleteDocument(ctx context.Context, id uuid.UUID) error
	DeleteEvalResultsByRun(ctx context.Context, evalRunID uuid.UUID) error
	DeleteEvalRule(ctx context.Context, id uuid.UUID) error
	DeleteEvalRulesBySuite(ctx context.Context, suiteID uuid.UUID) error
	DeleteEvalRun(ctx context.Context, id uuid.UUID) error
	DeleteEvalSuite(ctx context.Context, id uuid.UUID) error
	DeleteGenerationRun(ctx context.Context, id uuid.UUID) error
	DeleteModule(ctx context.Context, id uuid.UUID) error
	DeleteSession(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteUserRole(ctx context.Context, arg DeleteUserRoleParams) error
	GetAllTenants(ctx context.Context) ([]Tenant, error)
	GetArtifact(ctx context.Context, id uuid.UUID) (Artifact, error)
	GetAttempt(ctx context.Context, id uuid.UUID) (Attempt, error)
	GetDocument(ctx context.Context, id uuid.UUID) (Document, error)
	GetDocumentByModuleAndSourceURI(ctx context.Context, arg GetDocumentByModuleAndSourceURIParams) (Document, error)
	GetEvalResultByID(ctx context.Context, id uuid.UUID) (EvalResult, error)
	GetEvalRule(ctx context.Context, id uuid.UUID) (EvalRule, error)
	GetEvalRuleBySuiteAndType(ctx context.Context, arg GetEvalRuleBySuiteAndTypeParams) (EvalRule, error)
	GetEvalRunByID(ctx context.Context, id uuid.UUID) (EvalRun, error)
	GetEvalSuiteByID(ctx context.Context, id uuid.UUID) (EvalSuite, error)
	GetEvalSuiteByName(ctx context.Context, name string) (EvalSuite, error)
	GetGenerationRun(ctx context.Context, id uuid.UUID) (GenerationRun, error)
	GetLatestEvalRunForArtifact(ctx context.Context, artifactID uuid.UUID) (EvalRun, error)
	GetModule(ctx context.Context, id uuid.UUID) (Module, error)
	GetModuleByName(ctx context.Context, arg GetModuleByNameParams) (Module, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetTenantById(ctx context.Context, id uuid.UUID) (Tenant, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error)
	GetUserRoles(ctx context.Context, userID uuid.UUID) ([]UserRole, error)
	ListArtifactsByModule(ctx context.Context, moduleID uuid.UUID) ([]Artifact, error)
	ListArtifactsByModuleAndStatus(ctx context.Context, arg ListArtifactsByModuleAndStatusParams) ([]Artifact, error)
	ListArtifactsByModuleAndType(ctx context.Context, arg ListArtifactsByModuleAndTypeParams) ([]Artifact, error)
	ListAttemptsBySession(ctx context.Context, sessionID uuid.UUID) ([]Attempt, error)
	ListAttemptsByTenant(ctx context.Context, tenantID uuid.UUID) ([]Attempt, error)
	ListDocumentsByModule(ctx context.Context, moduleID uuid.UUID) ([]Document, error)
	ListEvalResultsByRule(ctx context.Context, ruleID uuid.UUID) ([]EvalResult, error)
	ListEvalResultsByRun(ctx context.Context, evalRunID uuid.UUID) ([]EvalResult, error)
	ListEvalRulesByEvalType(ctx context.Context, evalType string) ([]EvalRule, error)
	ListEvalRulesBySuite(ctx context.Context, suiteID uuid.UUID) ([]EvalRule, error)
	ListEvalRunsByArtifact(ctx context.Context, artifactID uuid.UUID) ([]EvalRun, error)
	ListEvalSuites(ctx context.Context) ([]EvalSuite, error)
	ListGenerationRunsByModule(ctx context.Context, moduleID uuid.UUID) ([]GenerationRun, error)
	ListGenerationRunsByStatus(ctx context.Context, arg ListGenerationRunsByStatusParams) ([]GenerationRun, error)
	ListModulesByTenant(ctx context.Context, tenantID uuid.UUID) ([]Module, error)
	ListSessionsByModule(ctx context.Context, moduleID uuid.UUID) ([]Session, error)
	ListSessionsByUser(ctx context.Context, userID uuid.UUID) ([]Session, error)
	ListUsersByRole(ctx context.Context, arg ListUsersByRoleParams) ([]User, error)
	ListUsersByTenant(ctx context.Context, tenantID uuid.UUID) ([]User, error)
	UpdateArtifactStatus(ctx context.Context, arg UpdateArtifactStatusParams) error
	UpdateDocument(ctx context.Context, arg UpdateDocumentParams) error
	UpdateEvalRule(ctx context.Context, arg UpdateEvalRuleParams) (EvalRule, error)
	UpdateEvalRunResult(ctx context.Context, arg UpdateEvalRunResultParams) (EvalRun, error)
	UpdateEvalSuite(ctx context.Context, arg UpdateEvalSuiteParams) (EvalSuite, error)
	UpdateGenerationRun(ctx context.Context, arg UpdateGenerationRunParams) error
	UpdateModule(ctx context.Context, arg UpdateModuleParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpsertEvalResult(ctx context.Context, arg UpsertEvalResultParams) (EvalResult, error)
}

var _ Querier = (*Queries)(nil)
