// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (tenant_id, module_id, user_id)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, user_id, module_id, status, mastery_state, created_at, completed_at
`

type CreateSessionParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ModuleID uuid.UUID `json:"module_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.TenantID, arg.ModuleID, arg.UserID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ModuleID,
		&i.Status,
		&i.MasteryState,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, tenant_id, user_id, module_id, status, mastery_state, created_at, completed_at FROM sessions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ModuleID,
		&i.Status,
		&i.MasteryState,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listSessionsByModule = `-- name: ListSessionsByModule :many
SELECT id, tenant_id, user_id, module_id, status, mastery_state, created_at, completed_at FROM sessions
WHERE module_id = $1
`

func (q *Queries) ListSessionsByModule(ctx context.Context, moduleID uuid.UUID) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByModule, moduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.ModuleID,
			&i.Status,
			&i.MasteryState,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByUser = `-- name: ListSessionsByUser :many
SELECT id, tenant_id, user_id, module_id, status, mastery_state, created_at, completed_at FROM sessions
WHERE user_id = $1
`

func (q *Queries) ListSessionsByUser(ctx context.Context, userID uuid.UUID) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.ModuleID,
			&i.Status,
			&i.MasteryState,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
