// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subjects.sql

package store

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createSubject = `-- name: CreateSubject :one
INSERT INTO subjects (user_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, description, created_at
`

type CreateSubjectParams struct {
	UserID      uuid.UUID      `json:"user_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateSubject(ctx context.Context, arg CreateSubjectParams) (Subject, error) {
	row := q.db.QueryRowContext(ctx, createSubject, arg.UserID, arg.Name, arg.Description)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSubject = `-- name: DeleteSubject :exec
DELETE FROM subjects WHERE id = $1
`

func (q *Queries) DeleteSubject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSubject, id)
	return err
}

const getSubject = `-- name: GetSubject :one
SELECT id, user_id, name, description, created_at FROM subjects
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSubject(ctx context.Context, id uuid.UUID) (Subject, error) {
	row := q.db.QueryRowContext(ctx, getSubject, id)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getSubjectByUserAndName = `-- name: GetSubjectByUserAndName :one
SELECT id, user_id, name, description, created_at FROM subjects
WHERE user_id = $1 AND name = $2 LIMIT 1
`

type GetSubjectByUserAndNameParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

func (q *Queries) GetSubjectByUserAndName(ctx context.Context, arg GetSubjectByUserAndNameParams) (Subject, error) {
	row := q.db.QueryRowContext(ctx, getSubjectByUserAndName, arg.UserID, arg.Name)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listSubjectsByUser = `-- name: ListSubjectsByUser :many
SELECT id, user_id, name, description, created_at FROM subjects
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSubjectsByUser(ctx context.Context, userID uuid.UUID) ([]Subject, error) {
	rows, err := q.db.QueryContext(ctx, listSubjectsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subject
	for rows.Next() {
		var i Subject
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubject = `-- name: UpdateSubject :one
UPDATE subjects
SET name = $2,
    description = $3
WHERE id = $1
RETURNING id, user_id, name, description, created_at
`

type UpdateSubjectParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) UpdateSubject(ctx context.Context, arg UpdateSubjectParams) (Subject, error) {
	row := q.db.QueryRowContext(ctx, updateSubject, arg.ID, arg.Name, arg.Description)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
