// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, is_active)
VALUES ($1, $2)
RETURNING id, name, is_active, created_at
`

type CreateTenantParams struct {
	Name     string `json:"name"`
	IsActive bool   `json:"is_active"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, createTenant, arg.Name, arg.IsActive)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getAllTenants = `-- name: GetAllTenants :many
SELECT id, name, is_active, created_at FROM tenants
`

func (q *Queries) GetAllTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.QueryContext(ctx, getAllTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tenant
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTenantById = `-- name: GetTenantById :one
SELECT id, name, is_active, created_at FROM tenants
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTenantById(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenantById, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
