// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/attempts/{id}": {
            "get": {
                "security": [
                    {
                        "OAuth2Auth": [
                            "read"
                        ]
                    }
                ],
                "description": "Learner+Teacher+Admin. Get a test attempt by ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "attempts"
                ],
                "summary": "Get attempt",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Attempt ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "501": {
                        "description": "not implemented",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/attempts/{id}/answers": {
            "post": {
                "security": [
                    {
                        "OAuth2Auth": [
                            "write"
                        ]
                    }
                ],
                "description": "Learner-only. Submit an answer for an attempt.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "attempts"
                ],
                "summary": "Submit answer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Attempt ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "501": {
                        "description": "not implemented",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/attempts/{id}/submit": {
            "post": {
                "security": [
                    {
                        "OAuth2Auth": [
                            "write"
                        ]
                    }
                ],
                "description": "Learner-only. Submit an attempt and finalize score.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "attempts"
                ],
                "summary": "Submit attempt",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Attempt ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "501": {
                        "description": "not implemented",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/eval-items/{id}/reviews": {
            "get": {
                "security": [
                    {
                        "OAuth2Auth": [
                            "read"
                        ]
                    }
                ],
                "description": "Admin-only. List review history for an eval item.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reviews"
                ],
                "summary": "List eval item reviews",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Eval Item ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "501": {
                        "description": "not implemented",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "OAuth2Auth": [
                            "write"
                        ]
                    }
                ],
                "description": "Teacher+Admin. Submit a review verdict for an eval item.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reviews"
                ],
                "summary": "Create eval item review",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Eval Item ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "501": {
                        "description": "not implemented",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/evals": {
            "get": {
                "security": [
                    {
                        "OAuth2Auth": [
                            "read"
                        ]
                    }
                ],
                "description": "Teacher+Learner. List published evals.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "evals"
                ],
                "summary": "List evals",
                "responses": {
                    "501": {
                        "description": "not implemented",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "OAuth2Auth": [
                            "write"
                        ]
                    }
                ],
                "description": "Admin-only. Create a new eval in draft.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "evals"
                ],
                "summary": "Create eval",
                "responses": {
                    "501": {
                        "description": "not implemented",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/evals/{id}": {
            "get": {
                "security": [
                    {
                        "OAuth2Auth": [
                            "read"
                        ]
                    }
                ],
                "description": "Teacher+Learner. Get a published eval by ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "evals"
                ],
                "summary": "Get eval",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Eval ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "501": {
                        "description": "not implemented",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/evals/{id}/attempts": {
            "post": {
                "security": [
                    {
                        "OAuth2Auth": [
                            "write"
                        ]
                    }
                ],
                "description": "Learner-only. Create a new attempt for an eval.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "attempts"
                ],
                "summary": "Start test attempt",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Eval ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "501": {
                        "description": "not implemented",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/evals/{id}/publish": {
            "post": {
                "security": [
                    {
                        "OAuth2Auth": [
                            "write"
                        ]
                    }
                ],
                "description": "Admin-only. Publish a draft eval (immutable after publish).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "evals"
                ],
                "summary": "Publish eval",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Eval ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "501": {
                        "description": "not implemented",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/oauth/token": {
            "post": {
                "description": "Issue or refresh OAuth2 tokens using supported grant types.\nSupported grant types:\n- password: exchange email + password for tokens\n- refresh_token: exchange refresh_token for new access token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "OAuth token endpoint",
                "parameters": [
                    {
                        "description": "OAuth Token Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/authdto.TokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OAuth2 token response",
                        "schema": {
                            "$ref": "#/definitions/authdto.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "invalid request or unsupported grant_type",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "invalid credentials",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/signup": {
            "post": {
                "description": "Create a new user account with email, password, and role",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Sign up a new user",
                "parameters": [
                    {
                        "description": "Signup Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/users.SignupRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/users.User"
                        }
                    },
                    "400": {
                        "description": "invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users": {
            "post": {
                "security": [
                    {
                        "OAuth2Auth": [
                            "write"
                        ]
                    }
                ],
                "description": "Create a new user with the provided details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create a new user",
                "parameters": [
                    {
                        "description": "Create User Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/users.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/users.User"
                        }
                    },
                    "400": {
                        "description": "invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/email/{email}": {
            "get": {
                "security": [
                    {
                        "OAuth2Auth": [
                            "read"
                        ]
                    }
                ],
                "description": "Retrieve a specific user by their email address",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user by email",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User Email",
                        "name": "email",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/users.User"
                        }
                    },
                    "400": {
                        "description": "invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "security": [
                    {
                        "OAuth2Auth": [
                            "read"
                        ]
                    }
                ],
                "description": "Retrieve a specific user by their unique ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/users.User"
                        }
                    },
                    "400": {
                        "description": "invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "OAuth2Auth": [
                            "write"
                        ]
                    }
                ],
                "description": "Remove a user from the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Delete user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "authdto.TokenRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "grant_type": {
                    "type": "string",
                    "example": "password"
                },
                "password": {
                    "type": "string",
                    "example": "secret123"
                },
                "refresh_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "authdto.TokenResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "expires_in": {
                    "type": "integer",
                    "example": 3600
                },
                "refresh_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "role": {
                    "type": "string",
                    "example": "user"
                },
                "token_type": {
                    "type": "string",
                    "example": "Bearer"
                }
            }
        },
        "users.CreateUserRequest": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/users.UserRoleType"
                }
            }
        },
        "users.SignupRequest": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/users.UserRoleType"
                }
            }
        },
        "users.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                }
            }
        },
        "users.UserRoleType": {
            "type": "string",
            "enum": [
                "ADMIN",
                "INSTRUCTOR",
                "LEARNER"
            ],
            "x-enum-varnames": [
                "UserRoleAdmin",
                "UserRoleInstructor",
                "UserRoleLearner"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
